// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// CreateClusterReader is a Reader for the CreateCluster structure.
type CreateClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateClusterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateClusterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateClusterCreated creates a CreateClusterCreated with default headers values
func NewCreateClusterCreated() *CreateClusterCreated {
	return &CreateClusterCreated{}
}

/*
CreateClusterCreated describes a response with status code 201, with default header values.

OK
*/
type CreateClusterCreated struct {
	Payload *models.Kluster
}

// IsSuccess returns true when this create cluster created response has a 2xx status code
func (o *CreateClusterCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create cluster created response has a 3xx status code
func (o *CreateClusterCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cluster created response has a 4xx status code
func (o *CreateClusterCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create cluster created response has a 5xx status code
func (o *CreateClusterCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create cluster created response a status code equal to that given
func (o *CreateClusterCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateClusterCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/clusters][%d] createClusterCreated  %+v", 201, o.Payload)
}

func (o *CreateClusterCreated) String() string {
	return fmt.Sprintf("[POST /api/v1/clusters][%d] createClusterCreated  %+v", 201, o.Payload)
}

func (o *CreateClusterCreated) GetPayload() *models.Kluster {
	return o.Payload
}

func (o *CreateClusterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Kluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterDefault creates a CreateClusterDefault with default headers values
func NewCreateClusterDefault(code int) *CreateClusterDefault {
	return &CreateClusterDefault{
		_statusCode: code,
	}
}

/*
CreateClusterDefault describes a response with status code -1, with default header values.

Error
*/
type CreateClusterDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create cluster default response
func (o *CreateClusterDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this create cluster default response has a 2xx status code
func (o *CreateClusterDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create cluster default response has a 3xx status code
func (o *CreateClusterDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create cluster default response has a 4xx status code
func (o *CreateClusterDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create cluster default response has a 5xx status code
func (o *CreateClusterDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create cluster default response a status code equal to that given
func (o *CreateClusterDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *CreateClusterDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/clusters][%d] CreateCluster default  %+v", o._statusCode, o.Payload)
}

func (o *CreateClusterDefault) String() string {
	return fmt.Sprintf("[POST /api/v1/clusters][%d] CreateCluster default  %+v", o._statusCode, o.Payload)
}

func (o *CreateClusterDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateClusterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
