// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetClusterInfoReader is a Reader for the GetClusterInfo structure.
type GetClusterInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClusterInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetClusterInfoDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetClusterInfoOK creates a GetClusterInfoOK with default headers values
func NewGetClusterInfoOK() *GetClusterInfoOK {
	return &GetClusterInfoOK{}
}

/*
GetClusterInfoOK describes a response with status code 200, with default header values.

OK
*/
type GetClusterInfoOK struct {
	Payload *models.KlusterInfo
}

// IsSuccess returns true when this get cluster info o k response has a 2xx status code
func (o *GetClusterInfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cluster info o k response has a 3xx status code
func (o *GetClusterInfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cluster info o k response has a 4xx status code
func (o *GetClusterInfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cluster info o k response has a 5xx status code
func (o *GetClusterInfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cluster info o k response a status code equal to that given
func (o *GetClusterInfoOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetClusterInfoOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/info][%d] getClusterInfoOK  %+v", 200, o.Payload)
}

func (o *GetClusterInfoOK) String() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/info][%d] getClusterInfoOK  %+v", 200, o.Payload)
}

func (o *GetClusterInfoOK) GetPayload() *models.KlusterInfo {
	return o.Payload
}

func (o *GetClusterInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KlusterInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterInfoDefault creates a GetClusterInfoDefault with default headers values
func NewGetClusterInfoDefault(code int) *GetClusterInfoDefault {
	return &GetClusterInfoDefault{
		_statusCode: code,
	}
}

/*
GetClusterInfoDefault describes a response with status code -1, with default header values.

Error
*/
type GetClusterInfoDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get cluster info default response
func (o *GetClusterInfoDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get cluster info default response has a 2xx status code
func (o *GetClusterInfoDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get cluster info default response has a 3xx status code
func (o *GetClusterInfoDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get cluster info default response has a 4xx status code
func (o *GetClusterInfoDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get cluster info default response has a 5xx status code
func (o *GetClusterInfoDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get cluster info default response a status code equal to that given
func (o *GetClusterInfoDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetClusterInfoDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/info][%d] GetClusterInfo default  %+v", o._statusCode, o.Payload)
}

func (o *GetClusterInfoDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/info][%d] GetClusterInfo default  %+v", o._statusCode, o.Payload)
}

func (o *GetClusterInfoDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetClusterInfoDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
