// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuthCallbackParams creates a new GetAuthCallbackParams object
// with the default values initialized.
func NewGetAuthCallbackParams() *GetAuthCallbackParams {
	var ()
	return &GetAuthCallbackParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthCallbackParamsWithTimeout creates a new GetAuthCallbackParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthCallbackParamsWithTimeout(timeout time.Duration) *GetAuthCallbackParams {
	var ()
	return &GetAuthCallbackParams{

		timeout: timeout,
	}
}

// NewGetAuthCallbackParamsWithContext creates a new GetAuthCallbackParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthCallbackParamsWithContext(ctx context.Context) *GetAuthCallbackParams {
	var ()
	return &GetAuthCallbackParams{

		Context: ctx,
	}
}

// NewGetAuthCallbackParamsWithHTTPClient creates a new GetAuthCallbackParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthCallbackParamsWithHTTPClient(client *http.Client) *GetAuthCallbackParams {
	var ()
	return &GetAuthCallbackParams{
		HTTPClient: client,
	}
}

/*GetAuthCallbackParams contains all the parameters to send to the API endpoint
for the get auth callback operation typically these are written to a http.Request
*/
type GetAuthCallbackParams struct {

	/*Code*/
	Code string
	/*State*/
	State string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth callback params
func (o *GetAuthCallbackParams) WithTimeout(timeout time.Duration) *GetAuthCallbackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth callback params
func (o *GetAuthCallbackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth callback params
func (o *GetAuthCallbackParams) WithContext(ctx context.Context) *GetAuthCallbackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth callback params
func (o *GetAuthCallbackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth callback params
func (o *GetAuthCallbackParams) WithHTTPClient(client *http.Client) *GetAuthCallbackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth callback params
func (o *GetAuthCallbackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCode adds the code to the get auth callback params
func (o *GetAuthCallbackParams) WithCode(code string) *GetAuthCallbackParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the get auth callback params
func (o *GetAuthCallbackParams) SetCode(code string) {
	o.Code = code
}

// WithState adds the state to the get auth callback params
func (o *GetAuthCallbackParams) WithState(state string) *GetAuthCallbackParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the get auth callback params
func (o *GetAuthCallbackParams) SetState(state string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthCallbackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param code
	qrCode := o.Code
	qCode := qrCode
	if qCode != "" {
		if err := r.SetQueryParam("code", qCode); err != nil {
			return err
		}
	}

	// query param state
	qrState := o.State
	qState := qrState
	if qState != "" {
		if err := r.SetQueryParam("state", qState); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
