// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetClusterCredentialsOIDCReader is a Reader for the GetClusterCredentialsOIDC structure.
type GetClusterCredentialsOIDCReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterCredentialsOIDCReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetClusterCredentialsOIDCOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetClusterCredentialsOIDCDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetClusterCredentialsOIDCOK creates a GetClusterCredentialsOIDCOK with default headers values
func NewGetClusterCredentialsOIDCOK() *GetClusterCredentialsOIDCOK {
	return &GetClusterCredentialsOIDCOK{}
}

/*GetClusterCredentialsOIDCOK handles this case with default header values.

OK
*/
type GetClusterCredentialsOIDCOK struct {
	Payload *models.Credentials
}

func (o *GetClusterCredentialsOIDCOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/credentials/oidc][%d] getClusterCredentialsOIdCOK  %+v", 200, o.Payload)
}

func (o *GetClusterCredentialsOIDCOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Credentials)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterCredentialsOIDCDefault creates a GetClusterCredentialsOIDCDefault with default headers values
func NewGetClusterCredentialsOIDCDefault(code int) *GetClusterCredentialsOIDCDefault {
	return &GetClusterCredentialsOIDCDefault{
		_statusCode: code,
	}
}

/*GetClusterCredentialsOIDCDefault handles this case with default header values.

Error
*/
type GetClusterCredentialsOIDCDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get cluster credentials o ID c default response
func (o *GetClusterCredentialsOIDCDefault) Code() int {
	return o._statusCode
}

func (o *GetClusterCredentialsOIDCDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/credentials/oidc][%d] GetClusterCredentialsOIDC default  %+v", o._statusCode, o.Payload)
}

func (o *GetClusterCredentialsOIDCDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
