// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClusterCredentialsOIDCParams creates a new GetClusterCredentialsOIDCParams object
// with the default values initialized.
func NewGetClusterCredentialsOIDCParams() *GetClusterCredentialsOIDCParams {
	var ()
	return &GetClusterCredentialsOIDCParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterCredentialsOIDCParamsWithTimeout creates a new GetClusterCredentialsOIDCParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClusterCredentialsOIDCParamsWithTimeout(timeout time.Duration) *GetClusterCredentialsOIDCParams {
	var ()
	return &GetClusterCredentialsOIDCParams{

		timeout: timeout,
	}
}

// NewGetClusterCredentialsOIDCParamsWithContext creates a new GetClusterCredentialsOIDCParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetClusterCredentialsOIDCParamsWithContext(ctx context.Context) *GetClusterCredentialsOIDCParams {
	var ()
	return &GetClusterCredentialsOIDCParams{

		Context: ctx,
	}
}

// NewGetClusterCredentialsOIDCParamsWithHTTPClient creates a new GetClusterCredentialsOIDCParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetClusterCredentialsOIDCParamsWithHTTPClient(client *http.Client) *GetClusterCredentialsOIDCParams {
	var ()
	return &GetClusterCredentialsOIDCParams{
		HTTPClient: client,
	}
}

/*GetClusterCredentialsOIDCParams contains all the parameters to send to the API endpoint
for the get cluster credentials o ID c operation typically these are written to a http.Request
*/
type GetClusterCredentialsOIDCParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cluster credentials o ID c params
func (o *GetClusterCredentialsOIDCParams) WithTimeout(timeout time.Duration) *GetClusterCredentialsOIDCParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster credentials o ID c params
func (o *GetClusterCredentialsOIDCParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster credentials o ID c params
func (o *GetClusterCredentialsOIDCParams) WithContext(ctx context.Context) *GetClusterCredentialsOIDCParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster credentials o ID c params
func (o *GetClusterCredentialsOIDCParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster credentials o ID c params
func (o *GetClusterCredentialsOIDCParams) WithHTTPClient(client *http.Client) *GetClusterCredentialsOIDCParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster credentials o ID c params
func (o *GetClusterCredentialsOIDCParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get cluster credentials o ID c params
func (o *GetClusterCredentialsOIDCParams) WithName(name string) *GetClusterCredentialsOIDCParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get cluster credentials o ID c params
func (o *GetClusterCredentialsOIDCParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterCredentialsOIDCParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
