// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetClusterCredentialsOIDCReader is a Reader for the GetClusterCredentialsOIDC structure.
type GetClusterCredentialsOIDCReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterCredentialsOIDCReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClusterCredentialsOIDCOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetClusterCredentialsOIDCDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetClusterCredentialsOIDCOK creates a GetClusterCredentialsOIDCOK with default headers values
func NewGetClusterCredentialsOIDCOK() *GetClusterCredentialsOIDCOK {
	return &GetClusterCredentialsOIDCOK{}
}

/*
GetClusterCredentialsOIDCOK describes a response with status code 200, with default header values.

OK
*/
type GetClusterCredentialsOIDCOK struct {
	Payload *models.Credentials
}

// IsSuccess returns true when this get cluster credentials o Id c o k response has a 2xx status code
func (o *GetClusterCredentialsOIDCOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cluster credentials o Id c o k response has a 3xx status code
func (o *GetClusterCredentialsOIDCOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cluster credentials o Id c o k response has a 4xx status code
func (o *GetClusterCredentialsOIDCOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cluster credentials o Id c o k response has a 5xx status code
func (o *GetClusterCredentialsOIDCOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cluster credentials o Id c o k response a status code equal to that given
func (o *GetClusterCredentialsOIDCOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetClusterCredentialsOIDCOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/credentials/oidc][%d] getClusterCredentialsOIdCOK  %+v", 200, o.Payload)
}

func (o *GetClusterCredentialsOIDCOK) String() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/credentials/oidc][%d] getClusterCredentialsOIdCOK  %+v", 200, o.Payload)
}

func (o *GetClusterCredentialsOIDCOK) GetPayload() *models.Credentials {
	return o.Payload
}

func (o *GetClusterCredentialsOIDCOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Credentials)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterCredentialsOIDCDefault creates a GetClusterCredentialsOIDCDefault with default headers values
func NewGetClusterCredentialsOIDCDefault(code int) *GetClusterCredentialsOIDCDefault {
	return &GetClusterCredentialsOIDCDefault{
		_statusCode: code,
	}
}

/*
GetClusterCredentialsOIDCDefault describes a response with status code -1, with default header values.

Error
*/
type GetClusterCredentialsOIDCDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get cluster credentials o ID c default response
func (o *GetClusterCredentialsOIDCDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get cluster credentials o ID c default response has a 2xx status code
func (o *GetClusterCredentialsOIDCDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get cluster credentials o ID c default response has a 3xx status code
func (o *GetClusterCredentialsOIDCDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get cluster credentials o ID c default response has a 4xx status code
func (o *GetClusterCredentialsOIDCDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get cluster credentials o ID c default response has a 5xx status code
func (o *GetClusterCredentialsOIDCDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get cluster credentials o ID c default response a status code equal to that given
func (o *GetClusterCredentialsOIDCDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetClusterCredentialsOIDCDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/credentials/oidc][%d] GetClusterCredentialsOIDC default  %+v", o._statusCode, o.Payload)
}

func (o *GetClusterCredentialsOIDCDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/clusters/{name}/credentials/oidc][%d] GetClusterCredentialsOIDC default  %+v", o._statusCode, o.Payload)
}

func (o *GetClusterCredentialsOIDCDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetClusterCredentialsOIDCDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
