// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterInfoParams creates a new GetClusterInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClusterInfoParams() *GetClusterInfoParams {
	return &GetClusterInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterInfoParamsWithTimeout creates a new GetClusterInfoParams object
// with the ability to set a timeout on a request.
func NewGetClusterInfoParamsWithTimeout(timeout time.Duration) *GetClusterInfoParams {
	return &GetClusterInfoParams{
		timeout: timeout,
	}
}

// NewGetClusterInfoParamsWithContext creates a new GetClusterInfoParams object
// with the ability to set a context for a request.
func NewGetClusterInfoParamsWithContext(ctx context.Context) *GetClusterInfoParams {
	return &GetClusterInfoParams{
		Context: ctx,
	}
}

// NewGetClusterInfoParamsWithHTTPClient creates a new GetClusterInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClusterInfoParamsWithHTTPClient(client *http.Client) *GetClusterInfoParams {
	return &GetClusterInfoParams{
		HTTPClient: client,
	}
}

/*
GetClusterInfoParams contains all the parameters to send to the API endpoint

	for the get cluster info operation.

	Typically these are written to a http.Request.
*/
type GetClusterInfoParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cluster info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterInfoParams) WithDefaults() *GetClusterInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cluster info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cluster info params
func (o *GetClusterInfoParams) WithTimeout(timeout time.Duration) *GetClusterInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster info params
func (o *GetClusterInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster info params
func (o *GetClusterInfoParams) WithContext(ctx context.Context) *GetClusterInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster info params
func (o *GetClusterInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster info params
func (o *GetClusterInfoParams) WithHTTPClient(client *http.Client) *GetClusterInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster info params
func (o *GetClusterInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get cluster info params
func (o *GetClusterInfoParams) WithName(name string) *GetClusterInfoParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get cluster info params
func (o *GetClusterInfoParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
