// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAuthLoginReader is a Reader for the GetAuthLogin structure.
type GetAuthLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 302:
		result := NewGetAuthLoginFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAuthLoginFound creates a GetAuthLoginFound with default headers values
func NewGetAuthLoginFound() *GetAuthLoginFound {
	return &GetAuthLoginFound{}
}

/*GetAuthLoginFound handles this case with default header values.

Redirect
*/
type GetAuthLoginFound struct {
}

func (o *GetAuthLoginFound) Error() string {
	return fmt.Sprintf("[GET /auth/login][%d] getAuthLoginFound ", 302)
}

func (o *GetAuthLoginFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
