// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClusterValuesParams creates a new GetClusterValuesParams object
// with the default values initialized.
func NewGetClusterValuesParams() *GetClusterValuesParams {
	var ()
	return &GetClusterValuesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterValuesParamsWithTimeout creates a new GetClusterValuesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetClusterValuesParamsWithTimeout(timeout time.Duration) *GetClusterValuesParams {
	var ()
	return &GetClusterValuesParams{

		timeout: timeout,
	}
}

// NewGetClusterValuesParamsWithContext creates a new GetClusterValuesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetClusterValuesParamsWithContext(ctx context.Context) *GetClusterValuesParams {
	var ()
	return &GetClusterValuesParams{

		Context: ctx,
	}
}

// NewGetClusterValuesParamsWithHTTPClient creates a new GetClusterValuesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetClusterValuesParamsWithHTTPClient(client *http.Client) *GetClusterValuesParams {
	var ()
	return &GetClusterValuesParams{
		HTTPClient: client,
	}
}

/*GetClusterValuesParams contains all the parameters to send to the API endpoint
for the get cluster values operation typically these are written to a http.Request
*/
type GetClusterValuesParams struct {

	/*Account*/
	Account string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cluster values params
func (o *GetClusterValuesParams) WithTimeout(timeout time.Duration) *GetClusterValuesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster values params
func (o *GetClusterValuesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster values params
func (o *GetClusterValuesParams) WithContext(ctx context.Context) *GetClusterValuesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster values params
func (o *GetClusterValuesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster values params
func (o *GetClusterValuesParams) WithHTTPClient(client *http.Client) *GetClusterValuesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster values params
func (o *GetClusterValuesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccount adds the account to the get cluster values params
func (o *GetClusterValuesParams) WithAccount(account string) *GetClusterValuesParams {
	o.SetAccount(account)
	return o
}

// SetAccount adds the account to the get cluster values params
func (o *GetClusterValuesParams) SetAccount(account string) {
	o.Account = account
}

// WithName adds the name to the get cluster values params
func (o *GetClusterValuesParams) WithName(name string) *GetClusterValuesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get cluster values params
func (o *GetClusterValuesParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterValuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account
	if err := r.SetPathParam("account", o.Account); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
