// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetOpenstackMetadataReader is a Reader for the GetOpenstackMetadata structure.
type GetOpenstackMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOpenstackMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOpenstackMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetOpenstackMetadataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetOpenstackMetadataOK creates a GetOpenstackMetadataOK with default headers values
func NewGetOpenstackMetadataOK() *GetOpenstackMetadataOK {
	return &GetOpenstackMetadataOK{}
}

/*
GetOpenstackMetadataOK describes a response with status code 200, with default header values.

OK
*/
type GetOpenstackMetadataOK struct {
	Payload *models.OpenstackMetadata
}

// IsSuccess returns true when this get openstack metadata o k response has a 2xx status code
func (o *GetOpenstackMetadataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get openstack metadata o k response has a 3xx status code
func (o *GetOpenstackMetadataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get openstack metadata o k response has a 4xx status code
func (o *GetOpenstackMetadataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get openstack metadata o k response has a 5xx status code
func (o *GetOpenstackMetadataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get openstack metadata o k response a status code equal to that given
func (o *GetOpenstackMetadataOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetOpenstackMetadataOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/openstack/metadata][%d] getOpenstackMetadataOK  %+v", 200, o.Payload)
}

func (o *GetOpenstackMetadataOK) String() string {
	return fmt.Sprintf("[GET /api/v1/openstack/metadata][%d] getOpenstackMetadataOK  %+v", 200, o.Payload)
}

func (o *GetOpenstackMetadataOK) GetPayload() *models.OpenstackMetadata {
	return o.Payload
}

func (o *GetOpenstackMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenstackMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOpenstackMetadataDefault creates a GetOpenstackMetadataDefault with default headers values
func NewGetOpenstackMetadataDefault(code int) *GetOpenstackMetadataDefault {
	return &GetOpenstackMetadataDefault{
		_statusCode: code,
	}
}

/*
GetOpenstackMetadataDefault describes a response with status code -1, with default header values.

Error
*/
type GetOpenstackMetadataDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get openstack metadata default response
func (o *GetOpenstackMetadataDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get openstack metadata default response has a 2xx status code
func (o *GetOpenstackMetadataDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get openstack metadata default response has a 3xx status code
func (o *GetOpenstackMetadataDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get openstack metadata default response has a 4xx status code
func (o *GetOpenstackMetadataDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get openstack metadata default response has a 5xx status code
func (o *GetOpenstackMetadataDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get openstack metadata default response a status code equal to that given
func (o *GetOpenstackMetadataDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetOpenstackMetadataDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/openstack/metadata][%d] GetOpenstackMetadata default  %+v", o._statusCode, o.Payload)
}

func (o *GetOpenstackMetadataDefault) String() string {
	return fmt.Sprintf("[GET /api/v1/openstack/metadata][%d] GetOpenstackMetadata default  %+v", o._statusCode, o.Payload)
}

func (o *GetOpenstackMetadataDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOpenstackMetadataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
