// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterKubeadmSecretParams creates a new GetClusterKubeadmSecretParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClusterKubeadmSecretParams() *GetClusterKubeadmSecretParams {
	return &GetClusterKubeadmSecretParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterKubeadmSecretParamsWithTimeout creates a new GetClusterKubeadmSecretParams object
// with the ability to set a timeout on a request.
func NewGetClusterKubeadmSecretParamsWithTimeout(timeout time.Duration) *GetClusterKubeadmSecretParams {
	return &GetClusterKubeadmSecretParams{
		timeout: timeout,
	}
}

// NewGetClusterKubeadmSecretParamsWithContext creates a new GetClusterKubeadmSecretParams object
// with the ability to set a context for a request.
func NewGetClusterKubeadmSecretParamsWithContext(ctx context.Context) *GetClusterKubeadmSecretParams {
	return &GetClusterKubeadmSecretParams{
		Context: ctx,
	}
}

// NewGetClusterKubeadmSecretParamsWithHTTPClient creates a new GetClusterKubeadmSecretParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClusterKubeadmSecretParamsWithHTTPClient(client *http.Client) *GetClusterKubeadmSecretParams {
	return &GetClusterKubeadmSecretParams{
		HTTPClient: client,
	}
}

/*
GetClusterKubeadmSecretParams contains all the parameters to send to the API endpoint

	for the get cluster kubeadm secret operation.

	Typically these are written to a http.Request.
*/
type GetClusterKubeadmSecretParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cluster kubeadm secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterKubeadmSecretParams) WithDefaults() *GetClusterKubeadmSecretParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cluster kubeadm secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterKubeadmSecretParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cluster kubeadm secret params
func (o *GetClusterKubeadmSecretParams) WithTimeout(timeout time.Duration) *GetClusterKubeadmSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster kubeadm secret params
func (o *GetClusterKubeadmSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster kubeadm secret params
func (o *GetClusterKubeadmSecretParams) WithContext(ctx context.Context) *GetClusterKubeadmSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster kubeadm secret params
func (o *GetClusterKubeadmSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster kubeadm secret params
func (o *GetClusterKubeadmSecretParams) WithHTTPClient(client *http.Client) *GetClusterKubeadmSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster kubeadm secret params
func (o *GetClusterKubeadmSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get cluster kubeadm secret params
func (o *GetClusterKubeadmSecretParams) WithName(name string) *GetClusterKubeadmSecretParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get cluster kubeadm secret params
func (o *GetClusterKubeadmSecretParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterKubeadmSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
