// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterCredentialsKubeadmParams creates a new GetClusterCredentialsKubeadmParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClusterCredentialsKubeadmParams() *GetClusterCredentialsKubeadmParams {
	return &GetClusterCredentialsKubeadmParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterCredentialsKubeadmParamsWithTimeout creates a new GetClusterCredentialsKubeadmParams object
// with the ability to set a timeout on a request.
func NewGetClusterCredentialsKubeadmParamsWithTimeout(timeout time.Duration) *GetClusterCredentialsKubeadmParams {
	return &GetClusterCredentialsKubeadmParams{
		timeout: timeout,
	}
}

// NewGetClusterCredentialsKubeadmParamsWithContext creates a new GetClusterCredentialsKubeadmParams object
// with the ability to set a context for a request.
func NewGetClusterCredentialsKubeadmParamsWithContext(ctx context.Context) *GetClusterCredentialsKubeadmParams {
	return &GetClusterCredentialsKubeadmParams{
		Context: ctx,
	}
}

// NewGetClusterCredentialsKubeadmParamsWithHTTPClient creates a new GetClusterCredentialsKubeadmParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClusterCredentialsKubeadmParamsWithHTTPClient(client *http.Client) *GetClusterCredentialsKubeadmParams {
	return &GetClusterCredentialsKubeadmParams{
		HTTPClient: client,
	}
}

/*
GetClusterCredentialsKubeadmParams contains all the parameters to send to the API endpoint

	for the get cluster credentials kubeadm operation.

	Typically these are written to a http.Request.
*/
type GetClusterCredentialsKubeadmParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cluster credentials kubeadm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterCredentialsKubeadmParams) WithDefaults() *GetClusterCredentialsKubeadmParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cluster credentials kubeadm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterCredentialsKubeadmParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cluster credentials kubeadm params
func (o *GetClusterCredentialsKubeadmParams) WithTimeout(timeout time.Duration) *GetClusterCredentialsKubeadmParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster credentials kubeadm params
func (o *GetClusterCredentialsKubeadmParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster credentials kubeadm params
func (o *GetClusterCredentialsKubeadmParams) WithContext(ctx context.Context) *GetClusterCredentialsKubeadmParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster credentials kubeadm params
func (o *GetClusterCredentialsKubeadmParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster credentials kubeadm params
func (o *GetClusterCredentialsKubeadmParams) WithHTTPClient(client *http.Client) *GetClusterCredentialsKubeadmParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster credentials kubeadm params
func (o *GetClusterCredentialsKubeadmParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get cluster credentials kubeadm params
func (o *GetClusterCredentialsKubeadmParams) WithName(name string) *GetClusterCredentialsKubeadmParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get cluster credentials kubeadm params
func (o *GetClusterCredentialsKubeadmParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterCredentialsKubeadmParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
