// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBoostrapConfigParams creates a new GetBoostrapConfigParams object
// with the default values initialized.
func NewGetBoostrapConfigParams() *GetBoostrapConfigParams {
	var ()
	return &GetBoostrapConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBoostrapConfigParamsWithTimeout creates a new GetBoostrapConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBoostrapConfigParamsWithTimeout(timeout time.Duration) *GetBoostrapConfigParams {
	var ()
	return &GetBoostrapConfigParams{

		timeout: timeout,
	}
}

// NewGetBoostrapConfigParamsWithContext creates a new GetBoostrapConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBoostrapConfigParamsWithContext(ctx context.Context) *GetBoostrapConfigParams {
	var ()
	return &GetBoostrapConfigParams{

		Context: ctx,
	}
}

// NewGetBoostrapConfigParamsWithHTTPClient creates a new GetBoostrapConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBoostrapConfigParamsWithHTTPClient(client *http.Client) *GetBoostrapConfigParams {
	var ()
	return &GetBoostrapConfigParams{
		HTTPClient: client,
	}
}

/*GetBoostrapConfigParams contains all the parameters to send to the API endpoint
for the get boostrap config operation typically these are written to a http.Request
*/
type GetBoostrapConfigParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get boostrap config params
func (o *GetBoostrapConfigParams) WithTimeout(timeout time.Duration) *GetBoostrapConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get boostrap config params
func (o *GetBoostrapConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get boostrap config params
func (o *GetBoostrapConfigParams) WithContext(ctx context.Context) *GetBoostrapConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get boostrap config params
func (o *GetBoostrapConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get boostrap config params
func (o *GetBoostrapConfigParams) WithHTTPClient(client *http.Client) *GetBoostrapConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get boostrap config params
func (o *GetBoostrapConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get boostrap config params
func (o *GetBoostrapConfigParams) WithName(name string) *GetBoostrapConfigParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get boostrap config params
func (o *GetBoostrapConfigParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetBoostrapConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
