// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOpenstackMetadataParams creates a new GetOpenstackMetadataParams object
// with the default values initialized.
func NewGetOpenstackMetadataParams() *GetOpenstackMetadataParams {

	return &GetOpenstackMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOpenstackMetadataParamsWithTimeout creates a new GetOpenstackMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOpenstackMetadataParamsWithTimeout(timeout time.Duration) *GetOpenstackMetadataParams {

	return &GetOpenstackMetadataParams{

		timeout: timeout,
	}
}

// NewGetOpenstackMetadataParamsWithContext creates a new GetOpenstackMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOpenstackMetadataParamsWithContext(ctx context.Context) *GetOpenstackMetadataParams {

	return &GetOpenstackMetadataParams{

		Context: ctx,
	}
}

// NewGetOpenstackMetadataParamsWithHTTPClient creates a new GetOpenstackMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOpenstackMetadataParamsWithHTTPClient(client *http.Client) *GetOpenstackMetadataParams {

	return &GetOpenstackMetadataParams{
		HTTPClient: client,
	}
}

/*GetOpenstackMetadataParams contains all the parameters to send to the API endpoint
for the get openstack metadata operation typically these are written to a http.Request
*/
type GetOpenstackMetadataParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get openstack metadata params
func (o *GetOpenstackMetadataParams) WithTimeout(timeout time.Duration) *GetOpenstackMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get openstack metadata params
func (o *GetOpenstackMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get openstack metadata params
func (o *GetOpenstackMetadataParams) WithContext(ctx context.Context) *GetOpenstackMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get openstack metadata params
func (o *GetOpenstackMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get openstack metadata params
func (o *GetOpenstackMetadataParams) WithHTTPClient(client *http.Client) *GetOpenstackMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get openstack metadata params
func (o *GetOpenstackMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetOpenstackMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
