// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetAuthCallbackReader is a Reader for the GetAuthCallback structure.
type GetAuthCallbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthCallbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAuthCallbackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetAuthCallbackDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAuthCallbackOK creates a GetAuthCallbackOK with default headers values
func NewGetAuthCallbackOK() *GetAuthCallbackOK {
	return &GetAuthCallbackOK{}
}

/*GetAuthCallbackOK handles this case with default header values.

OK
*/
type GetAuthCallbackOK struct {
	Payload *models.GetAuthCallbackOKBody
}

func (o *GetAuthCallbackOK) Error() string {
	return fmt.Sprintf("[GET /auth/callback][%d] getAuthCallbackOK  %+v", 200, o.Payload)
}

func (o *GetAuthCallbackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetAuthCallbackOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthCallbackDefault creates a GetAuthCallbackDefault with default headers values
func NewGetAuthCallbackDefault(code int) *GetAuthCallbackDefault {
	return &GetAuthCallbackDefault{
		_statusCode: code,
	}
}

/*GetAuthCallbackDefault handles this case with default header values.

Error
*/
type GetAuthCallbackDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get auth callback default response
func (o *GetAuthCallbackDefault) Code() int {
	return o._statusCode
}

func (o *GetAuthCallbackDefault) Error() string {
	return fmt.Sprintf("[GET /auth/callback][%d] GetAuthCallback default  %+v", o._statusCode, o.Payload)
}

func (o *GetAuthCallbackDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
