// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// InfoReader is a Reader for the Info structure.
type InfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInfoOK creates a InfoOK with default headers values
func NewInfoOK() *InfoOK {
	return &InfoOK{}
}

/*
InfoOK describes a response with status code 200, with default header values.

OK
*/
type InfoOK struct {
	Payload *models.Info
}

// IsSuccess returns true when this info o k response has a 2xx status code
func (o *InfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this info o k response has a 3xx status code
func (o *InfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this info o k response has a 4xx status code
func (o *InfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this info o k response has a 5xx status code
func (o *InfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this info o k response a status code equal to that given
func (o *InfoOK) IsCode(code int) bool {
	return code == 200
}

func (o *InfoOK) Error() string {
	return fmt.Sprintf("[GET /info][%d] infoOK  %+v", 200, o.Payload)
}

func (o *InfoOK) String() string {
	return fmt.Sprintf("[GET /info][%d] infoOK  %+v", 200, o.Payload)
}

func (o *InfoOK) GetPayload() *models.Info {
	return o.Payload
}

func (o *InfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Info)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
