// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// ListAPIVersionsReader is a Reader for the ListAPIVersions structure.
type ListAPIVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAPIVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAPIVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAPIVersionsOK creates a ListAPIVersionsOK with default headers values
func NewListAPIVersionsOK() *ListAPIVersionsOK {
	return &ListAPIVersionsOK{}
}

/*
ListAPIVersionsOK describes a response with status code 200, with default header values.

OK
*/
type ListAPIVersionsOK struct {
	Payload *models.APIVersions
}

// IsSuccess returns true when this list Api versions o k response has a 2xx status code
func (o *ListAPIVersionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list Api versions o k response has a 3xx status code
func (o *ListAPIVersionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Api versions o k response has a 4xx status code
func (o *ListAPIVersionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Api versions o k response has a 5xx status code
func (o *ListAPIVersionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list Api versions o k response a status code equal to that given
func (o *ListAPIVersionsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListAPIVersionsOK) Error() string {
	return fmt.Sprintf("[GET /api][%d] listApiVersionsOK  %+v", 200, o.Payload)
}

func (o *ListAPIVersionsOK) String() string {
	return fmt.Sprintf("[GET /api][%d] listApiVersionsOK  %+v", 200, o.Payload)
}

func (o *ListAPIVersionsOK) GetPayload() *models.APIVersions {
	return o.Payload
}

func (o *ListAPIVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIVersions)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
