// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// ListAPIVersionsReader is a Reader for the ListAPIVersions structure.
type ListAPIVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAPIVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListAPIVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewListAPIVersionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListAPIVersionsOK creates a ListAPIVersionsOK with default headers values
func NewListAPIVersionsOK() *ListAPIVersionsOK {
	return &ListAPIVersionsOK{}
}

/*ListAPIVersionsOK handles this case with default header values.

OK
*/
type ListAPIVersionsOK struct {
	Payload *models.APIVersions
}

func (o *ListAPIVersionsOK) Error() string {
	return fmt.Sprintf("[GET /api/][%d] listApiVersionsOK  %+v", 200, o.Payload)
}

func (o *ListAPIVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIVersions)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAPIVersionsUnauthorized creates a ListAPIVersionsUnauthorized with default headers values
func NewListAPIVersionsUnauthorized() *ListAPIVersionsUnauthorized {
	return &ListAPIVersionsUnauthorized{}
}

/*ListAPIVersionsUnauthorized handles this case with default header values.

Unauthorized
*/
type ListAPIVersionsUnauthorized struct {
}

func (o *ListAPIVersionsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/][%d] listApiVersionsUnauthorized ", 401)
}

func (o *ListAPIVersionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
