// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShowClusterParams creates a new ShowClusterParams object
// with the default values initialized.
func NewShowClusterParams() *ShowClusterParams {
	var ()
	return &ShowClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowClusterParamsWithTimeout creates a new ShowClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowClusterParamsWithTimeout(timeout time.Duration) *ShowClusterParams {
	var ()
	return &ShowClusterParams{

		timeout: timeout,
	}
}

// NewShowClusterParamsWithContext creates a new ShowClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowClusterParamsWithContext(ctx context.Context) *ShowClusterParams {
	var ()
	return &ShowClusterParams{

		Context: ctx,
	}
}

// NewShowClusterParamsWithHTTPClient creates a new ShowClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowClusterParamsWithHTTPClient(client *http.Client) *ShowClusterParams {
	var ()
	return &ShowClusterParams{
		HTTPClient: client,
	}
}

/*ShowClusterParams contains all the parameters to send to the API endpoint
for the show cluster operation typically these are written to a http.Request
*/
type ShowClusterParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show cluster params
func (o *ShowClusterParams) WithTimeout(timeout time.Duration) *ShowClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show cluster params
func (o *ShowClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show cluster params
func (o *ShowClusterParams) WithContext(ctx context.Context) *ShowClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show cluster params
func (o *ShowClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show cluster params
func (o *ShowClusterParams) WithHTTPClient(client *http.Client) *ShowClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show cluster params
func (o *ShowClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the show cluster params
func (o *ShowClusterParams) WithName(name string) *ShowClusterParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the show cluster params
func (o *ShowClusterParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ShowClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
