// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTerminateClusterParams creates a new TerminateClusterParams object
// with the default values initialized.
func NewTerminateClusterParams() *TerminateClusterParams {
	var ()
	return &TerminateClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTerminateClusterParamsWithTimeout creates a new TerminateClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTerminateClusterParamsWithTimeout(timeout time.Duration) *TerminateClusterParams {
	var ()
	return &TerminateClusterParams{

		timeout: timeout,
	}
}

// NewTerminateClusterParamsWithContext creates a new TerminateClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewTerminateClusterParamsWithContext(ctx context.Context) *TerminateClusterParams {
	var ()
	return &TerminateClusterParams{

		Context: ctx,
	}
}

// NewTerminateClusterParamsWithHTTPClient creates a new TerminateClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTerminateClusterParamsWithHTTPClient(client *http.Client) *TerminateClusterParams {
	var ()
	return &TerminateClusterParams{
		HTTPClient: client,
	}
}

/*TerminateClusterParams contains all the parameters to send to the API endpoint
for the terminate cluster operation typically these are written to a http.Request
*/
type TerminateClusterParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the terminate cluster params
func (o *TerminateClusterParams) WithTimeout(timeout time.Duration) *TerminateClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the terminate cluster params
func (o *TerminateClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the terminate cluster params
func (o *TerminateClusterParams) WithContext(ctx context.Context) *TerminateClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the terminate cluster params
func (o *TerminateClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the terminate cluster params
func (o *TerminateClusterParams) WithHTTPClient(client *http.Client) *TerminateClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the terminate cluster params
func (o *TerminateClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the terminate cluster params
func (o *TerminateClusterParams) WithName(name string) *TerminateClusterParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the terminate cluster params
func (o *TerminateClusterParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *TerminateClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
