ARG IMAGE

FROM keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/library/golang:1.16-alpine3.13 as builder
 
WORKDIR /
ADD api-liveness.go .
RUN CGO_ENABLED=0 go build -o /api-liveness /api-liveness.go 

FROM $IMAGE
COPY --from=builder /api-liveness /api-liveness
LABEL source_repository="https://github.com/kubernetes/kubernetes"
