version: "2"
linters:
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: false
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/sapcc/kubernikus)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
