ARG KUBERNIKUS_BINARIES_VERSION=:latest
FROM sapcc/kubernikus-binaries$KUBERNIKUS_BINARIES_VERSION as kubernikus-binaries

FROM alpine:3.6 as kubernikusctl
COPY --from=kubernikus-binaries /kubernikusctl /usr/local/bin/
CMD ["kubernikusctl"]
