FROM golang:1.9.2-alpine3.6 as builder
WORKDIR /go/src/github.com/sapcc/kubernikus/
RUN apk add --no-cache make git
RUN  go get golang.org/x/tools/cmd/goimports
COPY . .
ARG VERSION
RUN make all
RUN make test

FROM scratch as kubernikus-binaries
COPY --from=builder /go/src/github.com/sapcc/kubernikus/bin/linux/* /
