ARG VERSION=latest

FROM sapcc/kubernikus-binaries:$VERSION as kubernikus-binaries

FROM alpine:3.6 as nanny
MAINTAINER "Fabian Ruff <fabian.ruff@sap.com>"
RUN apk add --no-cache curl
RUN curl -Lo /bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.1/dumb-init_1.2.1_amd64 \
	&& chmod +x /bin/dumb-init \
	&& dumb-init -V
COPY --from=kubernikus-binaries /nanny /usr/local/bin/
ENTRYPOINT ["dumb-init", "--"]
CMD ["nanny"]
