FROM golang:1.9.0-alpine3.6 as builder
WORKDIR /go/src/github.com/sapcc/kubernikus/
RUN apk add --no-cache make
COPY . .
ARG VERSION
RUN make all

FROM scratch
COPY --from=builder /go/src/github.com/sapcc/kubernikus/bin/linux/* /
