ARG DIGEST                                
# default to latest
ARG VERSION=latest   

# Prefix wuth @ if set
ARG PDIGEST=${DIGEST:+@}$DIGEST           

# Prefix wuth : if set
ARG PVERSION=${VERSION:+:}$VERSION        

# Use digest if set. Version otherwise.
ARG TAG=${PDIGEST:-$PVERSION}             

FROM sapcc/kubernikus-docs-builder${TAG}
