ARG VERSION=latest
FROM sapcc/binaries:$VERSION as binaries

FROM alpine:3.6
MAINTAINER "Fabian Ruff <fabian.ruff@sap.com>"
RUN apk add --no-cache curl iptables
RUN curl -Lo /bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 \
	&& chmod +x /bin/dumb-init \
	&& dumb-init -V
COPY charts/ /etc/kubernikus/charts
COPY --from=binaries /apiserver /kubernikus /wormhole /usr/local/bin/
ENTRYPOINT ["dumb-init", "--"]
CMD ["apiserver"]
