apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: grafana
  annotations:
    vice-president: "true"
    prometheus.io/probe: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: | 
      rewrite ^/$ /dashboard/db/kubernikus?refresh=1m&orgId=1&kiosk=true redirect;
    {{- if .Values.authentication.enabled}}
    nginx.ingress.kubernetes.io/auth-tls-secret: "kubernikus-system/ca-crt"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "3"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
    {{ end }}

spec:
  tls:
     - secretName: grafana
       hosts: [grafana.{{ required "domain missing" .Values.domain }}]
  rules:
    - host: grafana.{{ required "domain missing" .Values.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: kubernikus-system-grafana
            servicePort: 80
