apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-server
  labels:
    app: prometheus
    component: "server"
  annotations:
    prometheus.io/configmap: "true"

data:
  prometheus.yml: |
{{ include "kubernikus-system/templates/_prometheus.yml.tpl" . | indent 4 }}
{{- if .Values.extra_scrape_config }}
{{ tpl .Values.extra_scrape_config . | indent 4 }}
{{- end}}
