{{- if .Values.authentication.enabled}}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: ca-crt 

data:
  ca.crt: {{ required "authentication.cacrt undefined" .Values.authentication.cacrt | b64enc | quote }}
{{- end }}
