#!/bin/bash
set -o errexit
set -o pipefail

if [ "$0" = '/usr/local/bin/helm' ]; then
	if [ -z "$HELM_HOST" ]; then
		if [ ! -f $HOME/.kube/config ]; then
      kubernikusctl credentials  
		fi
	fi
  exec /usr/bin/helm "$@"
fi

exec "$@"
