#!/bin/bash
set -o errexit
set -o pipefail

if [ "$0" = '/usr/local/bin/kubectl' ]; then
  if [ ! -f $HOME/.kube/config ]; then
    kubernikusctl auth init
  fi

  exec /usr/bin/kubectl "$@"
fi

exec "$@"

