{{- define "seed.storage-provisioner" -}}
  {{- if semverCompare ">= 1.20-0" .Capabilities.KubeVersion.Version -}}
    cinder.csi.openstack.org
  {{- else -}}
    kubernetes.io/cinder
  {{- end -}}
{{- end -}}
{{- define "seed.storage-expansion" -}}
  {{- if semverCompare ">= 1.20-0" .Capabilities.KubeVersion.Version -}}
    true
  {{- else -}}
    false
  {{- end -}}
{{- end -}}

{{- if .Values.openstack -}}

{{- range $az := .Values.openstack.azs -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-zone-{{ $az | trunc -1 }}
provisioner: {{ template "seed.storage-provisioner" $ }}
allowVolumeExpansion: {{ template "seed.storage-expansion" $ }}
volumeBindingMode: Immediate
parameters:
  availability: {{ $az }}
---
{{- end -}}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: {{ template "seed.storage-provisioner" $ }}
allowVolumeExpansion: {{ template "seed.storage-expansion" $ }}
volumeBindingMode: WaitForFirstConsumer

{{- end -}}
