{{- if semverCompare ">= 1.24-0" .Capabilities.KubeVersion.Version -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wormhole
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wormhole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wormhole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wormhole
subjects:
- kind: ServiceAccount
  name: wormhole
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wormhole
  namespace: kube-system
  labels:
    tier: node
    app: wormhole
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: wormhole
  template:
    metadata:
      labels:
        tier: node
        app: wormhole
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernikus.cloud.sap/cni
                operator: In
                values:
                - "true"
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: wormhole
      containers:
      - name: wormhole
        image: "{{ .Values.images.wormhole.repository }}:{{ .Values.version.kubernikus }}"
        command:
        - sh
        - -ec
        args:
        - |
          cp ${KUBE_CLIENT_CERT} /tmp/client-cert.livenessprobe
          exec wormhole client --listen {{ .Values.advertiseAddress }}:{{ .Values.advertisePort }} --health-check=false --kubeconfig=/var/lib/kubelet/kubeconfig
        env:
          - name: KUBE_CLIENT_CERT
            value: /var/lib/kubelet/pki/kubelet-client-current.pem
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
        livenessProbe:
          exec:
            command: [cmp, -s, $(KUBE_CLIENT_CERT), /tmp/client-cert.livenessprobe]
        volumeMounts:
        - name: config
          mountPath: /var/lib/kubelet
          readOnly: true
      volumes:
      - name: config
        hostPath:
          path: /var/lib/kubelet
{{- end }}
