apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernikus-prometheus

data:
  {{- $files := .Files }}
  {{ range tuple "aggregation.rules" "dns.alerts" "kubernetes.alerts" "kubernikus.alerts" "node.alerts" }}
  {{ . }}: |
{{ $files.Get . | indent 4 }}
  {{- end }}
  prometheus.yaml: |
{{ include "kubernikus-system/charts/prometheus/templates/_prometheus.yaml.tpl" . | indent 4 }}
{{- if .Values.extra_scrape_config }}
{{ tpl .Values.extra_scrape_config . | indent 4 }}
{{- end}}
