apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernikus-prometheus

data:
  # include all *.rules files
  {{- range $path, $bytes := .Files.Glob "*.rules" }}
  {{ printf "%s" $path }}: |
{{ printf "%s" $bytes | indent 4 }}
  {{ end }}

  # include all *.alerts files
  {{- range $path, $bytes := .Files.Glob "*.alerts" }}
  {{ printf "%s" $path }}: |
{{ printf "%s" $bytes | indent 4 }}
  {{ end }}

  prometheus.yaml: |
{{ include "kubernikus-system/charts/prometheus/templates/_prometheus.yaml.tpl" . | indent 4 }}
{{- if .Values.extra_scrape_config }}
{{ tpl .Values.extra_scrape_config . | indent 4 }}
{{- end}}
