package events

const (
	FailedCreateNode               = "FailedCreateNode"
	FailedDeleteNode               = "FailedDeleteNode"
	FailedDeorbitLoadBalancers     = "FailedDeorbitLoadBalancers"
	FailedDeorbitSnapshot          = "FailedDeorbitSnapshot"
	FailedDeorbitSnapshots         = "FailedDeorbitSnapshots"
	FailedDeorbitPVC               = "FailedDeorbitPVC"
	FailedDeorbitPVs               = "FailedDeorbitPVs"
	FailedDeorbitSelfDestruct      = "FailedDeorbitSelfDestruct"
	FailedDeorbitService           = "FailedDeorbitService"
	FailedDrainNode                = "FailedDrainNode"
	FailedRebootNode               = "FailedRebootNode"
	FailedReplaceNode              = "FailedReplaceNode"
	SuccessfulCreateNode           = "SuccessfulCreateNode"
	SuccessfulDeleteNode           = "SuccessfulDeleteNode"
	SuccessfulDeorbitLoadBalancers = "SuccessfulDeorbitLoadBalancers"
	SuccessfulDeorbitSnapshot      = "SuccessfulDeorbitSnapshot"
	SuccessfulDeorbitSnapshots     = "SuccessfulDeorbitSnapshots"
	SuccessfulDeorbitPVC           = "SuccessfulDeorbitPVC"
	SuccessfulDeorbitPVs           = "SuccessfulDeorbitPVs"
	SuccessfulDeorbitSelfDestruct  = "SuccessfulDeorbitSelfDestruct"
	SuccessfulDeorbitService       = "SuccessfulDeorbitService"
	SuccessfulDrainNode            = "SuccessfulDrainNode"
	SuccessfulRebootNode           = "SuccessfulRebootNode"
	SuccessfulReplaceNode          = "SuccessfulReplaceNode"
	WaitingForDeorbitLoadBalancers = "WaitingForDeorbitLoadBalancers"
	WaitingForDeorbitSnapshots     = "WaitingForDeorbitSnapshots"
	WaitingForDeorbitPVs           = "WaitingForDeorbitPVs"
)
