apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sniff-configmap
  namespace: k8sniff
data:
  k8sniff.json: |
    {
        "bind": {
            "host": "0.0.0.0",
            "port": 8443
        },
        "metrics": {
            "host": "0.0.0.0",
            "port": 9091,
            "path": "/metrics"
        },
        "kubernetes": {}
    }
