apiVersion: v1
kind: Service
metadata:
  name: k8sniff-ingress-lb
  namespace: k8sniff
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    role: k8sniff-ingress-lb
