apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sniff-configmap
data:
  k8sniff.json: |
    {
        "bind": {
            "host": "0.0.0.0",
            "port": 8443
        },
        "metrics": {
            "host": "0.0.0.0",
            "port": {{ default 9091 .Values.metrics_port }},
            "path": "/metrics"
        },
        "kubernetes": {}
    }
