apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sniff-ingress-lb
  labels:
    role: k8sniff-ingress-lb

spec:
  replicas: 1
  selector:
    matchLabels:
      role: k8sniff-ingress-lb
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ default "9091" .Values.metrics_port | quote }}
      labels:
        role: k8sniff-ingress-lb
    spec:
      containers:
      - image: {{ default "kubermatic/k8sniff" .Values.image }}:{{ default "v1.0" .Values.tag }}
        name: k8sniff-ingress-lb
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - -x
          - "/pipeline/source/k8sniff -logtostderr --v={{ default 9 .Values.log_level }} --config /etc/config/k8sniff.json"
        ports:
        - name: https
          containerPort: 8443
        - name: metrics
          containerPort: {{ default 9091 .Values.metrics_port }}
        volumeMounts:
        - name: k8sniff-config
          mountPath: /etc/config
          readOnly: true
      volumes:
        - name: k8sniff-config
          configMap:
            name: k8sniff-configmap
