{{- if .Values.api.tls_crt}}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: kubernikus-api

data:
  tls.crt: {{ required "api.tls_crt undefined" .Values.api.tls_crt | b64enc | quote }}
  tls.key: {{ required "api.tls_key undefined" .Values.api.tls_key | b64enc | quote }}
{{- end }}
