 {{ if .Values.dex.connectors.keystone.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kubernikus-dex-keystone
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  annotations:
    cloud.sap/inject-secrets: "true"
type: Opaque
data:
  adminUsername: {{ required "api.adminUser undefined" .Values.api.adminUser | b64enc | quote}}
  adminPassword: {{ required "api.adminPassword undefined" .Values.api.adminPassword | b64enc | quote}}
  adminUserDomain: {{ required "api.adminUserDomain undefined" .Values.api.adminUserDomain | b64enc | quote}}
  adminProject: {{ required "openstack.api.adminProject undefined" .Values.api.adminProject | b64enc | quote }}
  adminDomain: {{ required "openstack.api.adminDomain undefined" .Values.api.adminDomain | b64enc | quote }}
{{ end }}
