 {{ if .Values.dex.connectors.ldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name:  kubernikus-dex-ldap
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
type: Opaque
data:
  host: {{ required ".Values.dex.connectors.ldap.config.host undefined" .Values.dex.connectors.ldap.config.host | b64enc | quote}}
  bindDN: {{ required ".Values.dex.connectors.ldap.config.bindDN undefined" .Values.dex.connectors.ldap.config.bindDN | b64enc | quote}}
  bindPW: {{ required ".Values.dex.connectors.ldap.config.bindPW undefined" .Values.dex.connectors.ldap.config.bindPW | b64enc | quote}}
  userSearchBaseDN: {{ required ".Values.dex.connectors.ldap.userSearch.baseDN undefined" .Values.dex.connectors.ldap.userSearch.baseDN | b64enc | quote}}
  userSearchFilter: {{ required ".Values.dex.connectors.ldap.userSearch.filter undefined" .Values.dex.connectors.ldap.userSearch.filter | b64enc | quote}}
  groupSearchBaseDN: {{ required ".Values.dex.connectors.ldap.groupSearch.baseDN undefined" .Values.dex.connectors.ldap.groupSearch.baseDN | b64enc | quote}}
  groupSearchFilter: {{ required ".Values.dex.connectors.ldap.groupSearch.filter undefined" .Values.dex.connectors.ldap.groupSearch.filter | b64enc | quote}}
{{ end }}
