// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Event event
// swagger:model Event

type Event struct {

	// count
	Count int64 `json:"count"`

	// first timestamp
	FirstTimestamp strfmt.DateTime `json:"firstTimestamp,omitempty"`

	// last timestamp
	LastTimestamp strfmt.DateTime `json:"lastTimestamp,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`
}

/* polymorph Event count false */

/* polymorph Event firstTimestamp false */

/* polymorph Event lastTimestamp false */

/* polymorph Event message false */

/* polymorph Event reason false */

// Validate validates this event
func (m *Event) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Event) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Event) UnmarshalBinary(b []byte) error {
	var res Event
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
