// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KubeadmSecret kubeadm secret
//
// swagger:model KubeadmSecret
type KubeadmSecret struct {

	// secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this kubeadm secret
func (m *KubeadmSecret) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kubeadm secret based on context it is used
func (m *KubeadmSecret) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KubeadmSecret) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KubeadmSecret) UnmarshalBinary(b []byte) error {
	var res KubeadmSecret
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
