// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NodePoolInfo node pool info
// swagger:model NodePoolInfo

type NodePoolInfo struct {

	// healthy
	Healthy int64 `json:"healthy,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// running
	Running int64 `json:"running,omitempty"`

	// schedulable
	Schedulable int64 `json:"schedulable,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`
}

/* polymorph NodePoolInfo healthy false */

/* polymorph NodePoolInfo name false */

/* polymorph NodePoolInfo running false */

/* polymorph NodePoolInfo schedulable false */

/* polymorph NodePoolInfo size false */

// Validate validates this node pool info
func (m *NodePoolInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NodePoolInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodePoolInfo) UnmarshalBinary(b []byte) error {
	var res NodePoolInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
