// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OIDC o ID c
//
// swagger:model OIDC
type OIDC struct {

	// client ID
	ClientID string `json:"clientID,omitempty"`

	// issuer URL
	IssuerURL string `json:"issuerURL,omitempty"`
}

// Validate validates this o ID c
func (m *OIDC) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this o ID c based on context it is used
func (m *OIDC) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OIDC) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OIDC) UnmarshalBinary(b []byte) error {
	var res OIDC
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
