// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Principal principal
// swagger:model Principal

type Principal struct {

	// account id
	Account string `json:"account,omitempty"`

	// Identity Endpoint
	AuthURL string `json:"authUrl,omitempty"`

	// user's domain name
	Domain string `json:"domain,omitempty"`

	// userid
	ID string `json:"id,omitempty"`

	// username
	Name string `json:"name,omitempty"`

	// list of roles the user has in the given scope
	Roles []string `json:"roles"`
}

/* polymorph Principal account false */

/* polymorph Principal authUrl false */

/* polymorph Principal domain false */

/* polymorph Principal id false */

/* polymorph Principal name false */

/* polymorph Principal roles false */

// Validate validates this principal
func (m *Principal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRoles(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Principal) validateRoles(formats strfmt.Registry) error {

	if swag.IsZero(m.Roles) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Principal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Principal) UnmarshalBinary(b []byte) error {
	var res Principal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
