{
 "title": "Klusters",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kluster",
    "label": "Kluster",
    "query": "label_values(kubernikus_kluster_info{phase=\"Running\",kluster_name!~\"kubernikus-test-.*|e2e-.*\"},kluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod_name=~\"$kluster-.*\",container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod_name=~\"$kluster-.*\",container_name!=\"POD\"}) by (container_name) / max(label_replace(kube_pod_container_resource_limits_memory_bytes{pod=~\"$kluster-.*\",container!=\"POD\"},  \"container_name\", \"$1\", \"container\", \"(.*)\")) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$kluster-.*\",container_name!=\"POD\"}[5m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$kluster-.*\",container_name!=\"POD\"}[5m])) by (container_name) / max(label_replace(kube_pod_container_resource_limits_cpu_cores{pod=~\"$kluster-.*\",container!=\"POD\"},  \"container_name\", \"$1\", \"container\", \"(.*)\")) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(label_replace(kube_pod_container_status_restarts_total{pod=~\"$kluster.*\"}, \"app\", \"$2\", \"pod\", \"(.*)-(apiserver|etcd|scheduler|cmanager|backup)-[^-]+\")) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Container CPU Throttled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{pod_name=~\"$kluster-.*\",container_name!=\"POD\"}[5m])) by (container_name) ",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}