{
 "title": "Kubernikus",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container_runtime_version",
    "query": "label_values(kube_node_info,container_runtime_version)"
   },
   {
    "name": "kubelet_version",
    "query": "label_values(kube_node_info, kubelet_version)"
   },
   {
    "name": "coreos_version",
    "query": "label_values(kube_node_info, os_image)"
   },
   {
    "name": "kernel_version",
    "query": "label_values(kube_node_info, kernel_version)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 1 },
   "content": "\n\n\n![Kubernikus](https://github.com/sapcc/kubernikus/raw/master/assets/kubernikus_64x64.png)"
  },
  { "type": "text", "gridPos": { "h": 4, "w": 2, "x": 1, "y": 1 }, "content": "\n# Klusters\n\n" },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubernikus_kluster_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Creating",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubernikus_kluster_status_phase{phase=\"Creating\"})"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubernikus_kluster_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Terminating",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubernikus_kluster_status_phase{phase=\"Terminating\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 1, "x": 11, "y": 1 },
   "content": "\n\n\n![Kubernikus](https://github.com/sapcc/kubernikus/raw/master/assets/kubernikus_64x64.png)"
  },
  { "type": "text", "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 }, "content": "# Availability" },
  {
   "title": "Kubernikus",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=~\"https://kubernikus.*\",path=\"/\"}) ",
     "legendFormat": "API"
    },
    {
     "expr": "quantile_over_time(0.95, probe_duration_seconds{instance=~\"https://kubernikus.*\",kubernetes_name=\"kubernikus-api\"}[24h]) ",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Klusters",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_http_duration_seconds{path=\"/\"})",
     "legendFormat": "API"
    },
    {
     "expr": "avg(quantile_over_time(0.5, probe_duration_seconds{path=\"/\"}[24h]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{path=\"/\", kubernetes_name!~\"e2e.*|kubernikus-test.*\"} < 1 AND ON (kubernetes_name) label_replace(kubernikus_kluster_status_phase{phase=\"Running\"}, \"kubernetes_name\", \"$1\", \"kluster_id\", \"(.*)\")",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 2, "x": 1, "y": 5 }, "content": "\n# Updates\n\n" },
  {
   "title": "Status by Node",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kubernikus_servicing_nodes_state_waiting) without (instance)) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Status by Kluster",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(max(kubernikus_servicing_nodes_state_waiting) without (instance)) by (kluster_id,state) > 0) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kubernikus_servicing_nodes_state_updating{state=\"failed\"}) without (instance))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 2, "x": 12, "y": 5 }, "content": "# Versions" },
  {
   "title": "Nodes / Kubelet",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kubernikus_servicing_nodes_version_kubelet) without (instance)) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Nodes / CoreOS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kubernikus_servicing_nodes_version_osimage) without (instance)) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Klusters / API",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kubernikus_kluster_info) without (instance,kubernetes_pod_name,pod_template_hash)) by (api_version)",
     "legendFormat": "{{api_version}}"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 11 },
   "content": "\n\n\n![Kubernetes](https://avatars1.githubusercontent.com/u/13629408?s=64&v=4)"
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 1, "y": 11 }, "content": "# Capacity" },
  {
   "title": "Control Plane",
   "type": "text",
   "gridPos": { "h": 6, "w": 2, "x": 3, "y": 11 },
   "content": "<style>\n  table.info td {\n    border: none;\n    background: none;\n  }   \n  table.info th {\n    border: none;\n    font-weight: bold;\n    background: none;\n  } \n</style>\n\n<table class=\"info\">\n<tr><th>CoreOS</th><td>$coreos_version</td></tr>\n<tr><th>Kernel</th><td>$kernel_version</td></tr>\n<tr><th>Kubernetes</th><td>$kubelet_version</td></tr>\n<tr><th>Docker</th><td>$container_runtime_version</td></tr>\n</table>\n"
  },
  {
   "title": "Remaining CPUs",
   "type": "singlestat",
   "description": "Out of CPU in this many Klusters",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_cpu_cores) - sum(kube_pod_container_resource_requests_cpu_cores)) / (sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"kubernikus\"}) / sum(kubernikus_kluster_status_phase))"
    }
   ]
  },
  {
   "title": "Remaining Memory",
   "type": "singlestat",
   "description": "Out of Memory in this many Klusters",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_memory_bytes) - sum(kube_pod_container_resource_requests_memory_bytes)) / (sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"kubernikus\"}) / sum(kubernikus_kluster_status_phase))"
    }
   ]
  },
  {
   "title": "Remaining Pods",
   "type": "singlestat",
   "description": "Out of Podsin this many Klusters",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_pods) - sum(kube_pod_container_info)) / 4"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 11, "y": 11 },
   "content": "\n\n\n![Openstack](https://raw.githubusercontent.com/sapcc/kubernikus/master/assets/openstack_64x64.png) \n"
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 }, "content": "# Capacity" },
  {
   "title": "Volumes",
   "type": "singlestat",
   "description": "Out of Volumes in this many Klusters",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "limes_project_quota{project=\"kubernikus\",resource=\"volumes\",domain=\"ccadmin\"} - limes_project_usage{project=\"kubernikus\",resource=\"volumes\",domain=\"ccadmin\"}"
    }
   ]
  },
  {
   "title": "Cinder",
   "type": "singlestat",
   "description": "Out of Volumes in this many Klusters",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(limes_project_quota{project=\"kubernikus\",resource=\"capacity\",domain=\"ccadmin\",service=\"volumev2\"} - limes_project_usage{project=\"kubernikus\",resource=\"capacity\",domain=\"ccadmin\",service=\"volumev2\"}) / 10"
    },
    {}
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "limes_project_quota{project=\"kubernikus\",resource=\"instances\",domain=\"ccadmin\"} - limes_project_usage{project=\"kubernikus\",resource=\"instances\",domain=\"ccadmin\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(limes_project_quota{project=\"kubernikus\",resource=\"cores\",domain=\"ccadmin\"} - limes_project_usage{project=\"kubernikus\",resource=\"cores\",domain=\"ccadmin\"}) / 8"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(limes_project_quota{project=\"kubernikus\",resource=\"ram\",domain=\"ccadmin\"} - limes_project_usage{project=\"kubernikus\",resource=\"ram\",domain=\"ccadmin\"}) / 16000"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 1, "y": 14 }, "content": "# Usage" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=~\"system|user|iowait\"}[5m])) by (instance) / sum(irate(node_cpu_seconds_total{}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": " (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes  ) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": " count(kube_pod_info) by (node) / sum(kube_node_status_capacity_pods)  by (node)",
     "legendFormat": "{{node}}"
    },
    {}
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 12, "y": 14 }, "content": "# Usage" },
  {
   "title": "Volumes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "limes_project_usage{project=\"kubernikus\",resource=\"volumes\",domain=\"ccadmin\"} / limes_project_quota{project=\"kubernikus\",resource=\"volumes\",domain=\"ccadmin\"} * 100",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Cinder",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod_name=~\".*-etcd-.*\",image!~\".*pause.*\"}) / sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"kubernikus\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "limes_project_usage{project=\"kubernikus\",resource=\"instances\",domain=\"ccadmin\"} / limes_project_quota{project=\"kubernikus\",resource=\"instances\",domain=\"ccadmin\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "limes_project_usage{project=\"kubernikus\",resource=\"cores\",domain=\"ccadmin\"} / limes_project_quota{project=\"kubernikus\",resource=\"cores\",domain=\"ccadmin\"} "
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "limes_project_usage{project=\"kubernikus\",resource=\"ram\",domain=\"ccadmin\"} / limes_project_quota{project=\"kubernikus\",resource=\"ram\",domain=\"ccadmin\"}"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Average Kluster Boot Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 18 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kubernikus_kluster_boot_duration_sum / kubernikus_kluster_boot_duration_count",
     "legendFormat": "Boot Time"
    }
   ]
  },
  {
   "title": "CPU Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"kubernikus\",name=~\".*(etcd|manager|scheduler|apiserver).*\",image!~\".*pause.*\"}[1h]), \"container\", \"$1\", \"name\", \".*(etcd|manager|scheduler|apiserver).*\")) by (container) / sum(label_replace(kube_pod_container_resource_requests_cpu_cores{container=~\"apiserver|etcd|scheduler|controller-manager\"}, \"container\", \"$1\", \"container\", \".*(etcd|manager|scheduler|apiserver)\")) by (container)",
     "legendFormat": "{{container}}"
    },
    {}
   ]
  },
  {
   "title": "Memory Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"kubernikus\",name=~\".*(etcd|manager|scheduler|apiserver).*\",image!~\".*pause.*\"}, \"container\", \"$1\", \"name\", \".*(etcd|manager|scheduler|apiserver).*\")) by (container) / sum(label_replace(kube_pod_container_resource_requests_memory_bytes{container=~\"apiserver|etcd|scheduler|controller-manager\"}, \"container\", \"$1\", \"container\", \".*(etcd|manager|scheduler|apiserver)\")) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Deorbit Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "60 * sum(rate(kubernikus_deorbit_successful_operation_total[11m]))",
     "legendFormat": "Sucess"
    },
    {
     "expr": "60 * sum(rate(kubernikus_deorbit_failed_operation_total[11m]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Launch Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "60 * sum(rate(kubernikus_launch_successful_operation_total[11m]))",
     "legendFormat": "Sucess"
    },
    {
     "expr": "60 * sum(rate(kubernikus_launch_failed_operation_total[11m]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "GoRoutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{app=\"kubernikus\"})"
    },
    { "expr": "go_rout", "legendFormat": "24h Average" }
   ]
  }
 ]
}