auth_master: &auth_master
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-master
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-master
  KUBERNIKUS_URL: https://k-master.admin.cloud.sap

auth_feature: &auth_feature
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-feature
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-feature
  KUBERNIKUS_URL: https://k-feature.admin.cloud.sap

auth_infra: &auth_infra
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-infra
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-infra
  KUBERNIKUS_URL: https://k-infra.admin.cloud.sap

auth_staging: &auth_staging
  OS_AUTH_URL: https://identity-3.staging.cloud.sap/v3
  OS_USERNAME: ((kubernikus-staging-username))
  OS_PASSWORD: ((kubernikus-staging-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-staging
  KUBERNIKUS_URL: https://k-staging.admin.cloud.sap

auth_qa-de-1: &auth_qa-de-1
  OS_AUTH_URL: https://identity-3.qa-de-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-qa-username))
  OS_PASSWORD: ((kubernikus-qa-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-qa-de-1 
  KUBERNIKUS_URL: https://k-qa-de-1.admin.cloud.sap

auth_ap-au-1: &auth_ap-au-1
  OS_AUTH_URL: https://identity-3.ap-au-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-ap-au-1
  KUBERNIKUS_URL: https://k-ap-au-1.admin.cloud.sap

auth_eu-de-1: &auth_eu-de-1
  OS_AUTH_URL: https://identity-3.eu-de-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-eu-de-1 
  KUBERNIKUS_URL: https://k-eu-de-1.admin.cloud.sap

auth_eu-de-1: &auth_eu-de-2
  OS_AUTH_URL: https://identity-3.eu-de-2.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-eu-de-2 
  KUBERNIKUS_URL: https://k-eu-de-2.admin.cloud.sap

auth_eu-nl-1: &auth_eu-nl-1
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-eu-nl-1 
  KUBERNIKUS_URL: https://k-eu-nl-1.admin.cloud.sap

auth_na-us-1: &auth_na-us-1
  OS_AUTH_URL: https://identity-3.na-us-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-na-us-1
  KUBERNIKUS_URL: https://k-na-us-1.admin.cloud.sap

auth_e2e_eu-de-1: &auth_e2e_ap-au-1
  OS_AUTH_URL: https://identity-3.ap-au-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-e2e
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: e2e 
  KUBERNIKUS_URL: https://kubernikus.ap-au-1.cloud.sap

auth_e2e_eu-nl-1: &auth_e2e_eu-nl-1
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-e2e
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: e2e 
  KUBERNIKUS_URL: https://kubernikus-master.eu-nl-1.cloud.sap

auth_e2e_eu-de-1: &auth_e2e_eu-de-1
  OS_AUTH_URL: https://identity-3.eu-de-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-e2e
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: e2e 
  KUBERNIKUS_URL: https://kubernikus.eu-de-1.cloud.sap

auth_e2e_eu-de-1: &auth_e2e_eu-de-2
  OS_AUTH_URL: https://identity-3.eu-de-2.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-e2e
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: e2e 
  KUBERNIKUS_URL: https://kubernikus.eu-de-2.cloud.sap

auth_e2e_eu-nl-1: &auth_e2e_na-us-1
  OS_AUTH_URL: https://identity-3.na-us-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-prod-username))
  OS_PASSWORD: ((kubernikus-prod-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-e2e
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: e2e 
  KUBERNIKUS_URL: https://kubernikus.na-us-1.cloud.sap

auth_e2e_qa-de-1: &auth_e2e_qa-de-1
  OS_AUTH_URL: https://identity-3.qa-de-1.cloud.sap/v3
  OS_USERNAME: ((kubernikus-qa-username))
  OS_PASSWORD: ((kubernikus-qa-password))
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-e2e
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: e2e
  KUBERNIKUS_URL: https://kubernikus.qa-de-1.cloud.sap

resources:

  - name: master.builds
    type: gh-status
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      owner:    sapcc
      repo:     kubernikus
      access_token: ((github-com-access-token))
      branch: master
      depth: 1

  - name: feature.builds
    type: gh-status
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      owner:    sapcc
      repo:     kubernikus
      access_token: ((github-com-access-token))
      branch: feature 
      depth: 1

  - name: infra.builds
    type: gh-status
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      owner:    sapcc
      repo:     kubernikus
      access_token: ((github-com-access-token))
      branch: infra 
      depth: 1

  - name: secrets.git
    type: git
    source:
      uri:         git@github.wdf.sap.corp:cc/secrets.git
      private_key: ((secrets-ssh-key))
      branch:      master
      depth: 1

  - name: daily
    type: time
    source: {interval: 24h}

  - name: hourly 
    type: time
    source: {interval: 1h}
  - name: slack
    type: slack-alert
    source:
      url: ((slack-webhook-url))
      channel: '#kubernikus'

resource_types:
  - name: time-version
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/time-version-resource
      tag: v2
  - name: slack-alert
    type: docker-image
    source:
      repository: arbourd/concourse-slack-alert-resource
  - name: gh-status
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/ghstatus-resource
      tag: latest

jobs:
  - name: master 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          trigger: true
      - aggregate:
        - task: kubernikus 
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_master
        - task: kubernikus-system 
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_master
    on_success: { put: slack, params: {alert_type: fixed } }
    on_failure: { put: slack, params: {alert_type: broke } }
    on_abort:   { put: slack, params: {alert_type: broke } }

  - name: feature 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: feature.builds
          trigger: true
      - aggregate:
        - task: kubernikus 
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_feature
        - task: kubernikus-system 
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_feature

  - name: infra 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: infra.builds
          trigger: true
      - aggregate:
        - task: k-infra
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-infra
            GITHUB_TOKEN: ((github-access-token))

  - name: e2e
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [master]
          trigger: true
      - task: e2e_tests
        file: kubernikus.builds/ci/task_e2e_tests.yaml
        timeout: 2h
        params:
          <<: *auth_e2e_eu-nl-1
    on_success: { put: slack, params: {alert_type: fixed } }
    on_failure: { put: slack, params: {alert_type: broke } }
    on_abort:   { put: slack, params: {alert_type: broke } }

  - name: conformance 
    serial: true
    build_logs_to_retain: 30
    plan:
      - aggregate:
        - get: kubernikus.builds
          resource: master.builds
          passed: [e2e]
        - get: daily
          trigger: true

  - name: prod 
    serial: true
    plan:
      - get: kubernikus.builds
        resource: master.builds
        passed: [e2e]

  - name: emea 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [prod]
          trigger: true
      - aggregate:
        - task: kubernikus_eu-de-1
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_eu-de-1
        - task: kubernikus_eu-de-2
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_eu-de-2
        - task: kubernikus_eu-nl-1
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_eu-nl-1
        - task: kubernikus-system_eu-de-1
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_eu-de-1
        - task: kubernikus-system_eu-de-2
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_eu-de-2
        - task: kubernikus-system_eu-nl-1
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_eu-nl-1

  - name: asia
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [prod]
          trigger: true
      - aggregate:
        - task: kubernikus_ap-au-1
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_ap-au-1
        - task: kubernikus-system_ap-au-1
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_ap-au-1

  - name: americas 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [prod]
          trigger: true
      - aggregate:
        - task: kubernikus_na-us-1
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_na-us-1
        - task: kubernikus-system_na-us-1
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_na-us-1

  - name: admin 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [prod]
          trigger: true
      - aggregate:
        - task: k-master 
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-master
            GITHUB_TOKEN: ((github-access-token))
        - task: k-feature
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-feature
            GITHUB_TOKEN: ((github-access-token))
        - task: k-ap-au-1
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-ap-au-1
            GITHUB_TOKEN: ((github-access-token))
        - task: k-eu-de-1
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-eu-de-1
            GITHUB_TOKEN: ((github-access-token))
        - task: k-eu-de-2
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-eu-de-2
            GITHUB_TOKEN: ((github-access-token))
        - task: k-eu-nl-1
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-eu-nl-1
            GITHUB_TOKEN: ((github-access-token))
        - task: k-na-us-1
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-na-us-1
            GITHUB_TOKEN: ((github-access-token))

  - name: staging 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: feature.builds
          passed: [feature]
          trigger: true
      - aggregate:
        - task: k-staging
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-staging
            GITHUB_TOKEN: ((github-access-token))
        - task: kubernikus
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_staging
        - task: kubernikus-system
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_staging

  - name: qa
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: feature.builds
          passed: [feature]
          trigger: true
      - aggregate:
        - task: k-qa-de-1
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-qa-de-1
            GITHUB_TOKEN: ((github-access-token))
        - task: kubernikus
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_qa-de-1
        - task: kubernikus-system
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_qa-de-1


  - name: soak_ap-au-1
    serial: true
    build_logs_to_retain: 168
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [e2e]
        - get: hourly 
          trigger: true
      - task: e2e_tests
        file: kubernikus.builds/ci/task_e2e_tests.yaml
        timeout: 45m
        params:
          <<: *auth_e2e_ap-au-1
    on_success: { put: slack, params: {alert_type: fixed } }
    on_failure: { put: slack, params: {alert_type: broke } }
    on_abort:   { put: slack, params: {alert_type: broke } }

  - name: soak_eu-de-1
    serial: true
    build_logs_to_retain: 168
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [e2e]
        - get: hourly 
          trigger: true
      - task: e2e_tests
        file: kubernikus.builds/ci/task_e2e_tests.yaml
        timeout: 45m
        params:
          <<: *auth_e2e_eu-de-1
    on_success: { put: slack, params: {alert_type: fixed } }
    on_failure: { put: slack, params: {alert_type: broke } }
    on_abort:   { put: slack, params: {alert_type: broke } }

  - name: soak_eu-de-2
    serial: true
    build_logs_to_retain: 168
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [e2e]
        - get: hourly 
          trigger: true
      - task: e2e_tests
        file: kubernikus.builds/ci/task_e2e_tests.yaml
        timeout: 45m
        params:
          <<: *auth_e2e_eu-de-2
    on_success: { put: slack, params: {alert_type: fixed } }
    on_failure: { put: slack, params: {alert_type: broke } }
    on_abort:   { put: slack, params: {alert_type: broke } }

  - name: soak_na-us-1
    serial: true
    build_logs_to_retain: 168
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [e2e]
        - get: hourly 
          trigger: true
      - task: e2e_tests
        file: kubernikus.builds/ci/task_e2e_tests.yaml
        timeout: 45m
        params:
          <<: *auth_e2e_na-us-1
    on_success: { put: slack, params: {alert_type: fixed } }
    on_failure: { put: slack, params: {alert_type: broke } }
    on_abort:   { put: slack, params: {alert_type: broke } }

  - name: soak_qa-de-1
    build_logs_to_retain: 168
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [e2e]
        - get: hourly 
          trigger: true
      - task: e2e_tests
        file: kubernikus.builds/ci/task_e2e_tests.yaml
        timeout: 45m
        params:
          <<: *auth_e2e_qa-de-1
    on_success: { put: slack, params: {alert_type: fixed } }
    on_failure: { put: slack, params: {alert_type: broke } }
    on_abort:   { put: slack, params: {alert_type: broke } }
