post_failure_to_slack: &post_failure_to_slack
  put: slack-alert
  params:
    channel: '#kubernikus'
    username: 'Concourse'
    icon_emoji: ':airplane:'
    silent: 'true'
    text: |
      :boom: <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME $BUILD_JOB_NAME job #$BUILD_NAME failed>
      To debug run `fly hijack -j $BUILD_PIPELINE_NAME/$BUILD_JOB_NAME -b $BUILD_NAME`

auth_master: &auth_master
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: {{kubernikus-eu-nl-1-username}}
  OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-master
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-master
  KUBERNIKUS_URL: https://k-master.admin.cloud.sap

auth_feature: &auth_feature
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: {{kubernikus-eu-nl-1-username}}
  OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-feature
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-feature
  KUBERNIKUS_URL: https://k-feature.admin.cloud.sap

auth_e2e: &auth_e2e
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: {{kubernikus-eu-nl-1-username}}
  OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus-e2e
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: e2e 
  KUBERNIKUS_URL: https://kubernikus-master.eu-nl-1.cloud.sap

auth_staging: &auth_staging
  OS_AUTH_URL: https://identity-3.staging.cloud.sap/v3
  OS_USERNAME: {{kubernikus-staging-username}}
  OS_PASSWORD: {{kubernikus-staging-password}}
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-staging
  KUBERNIKUS_URL: https://k-staging.admin.cloud.sap

auth_eu-nl-1: &auth_eu-nl-1
  OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
  OS_USERNAME: {{kubernikus-eu-nl-1-username}}
  OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-eu-nl-1 
  KUBERNIKUS_URL: https://k-eu-nl-1.admin.cloud.sap

auth_na-us-1: &auth_na-us-1
  OS_AUTH_URL: https://identity-3.na-us-1.cloud.sap/v3
  OS_USERNAME: {{kubernikus-na-us-1-username}}
  OS_PASSWORD: {{kubernikus-na-us-1-password}}
  OS_USER_DOMAIN_NAME: ccadmin
  OS_PROJECT_NAME: kubernikus
  OS_PROJECT_DOMAIN_NAME: ccadmin
  KUBERNIKUS_NAME: k-na-us-1
  KUBERNIKUS_URL: https://k-na-us-1.admin.cloud.sap

resources:

  - name: master.builds
    type: gh-status
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      owner:    sapcc
      repo:     kubernikus
      access_token: ((github-com-access-token))
      branch: master
      depth: 1

  - name: feature.builds
    type: gh-status
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      owner:    sapcc
      repo:     kubernikus
      access_token: ((github-com-access-token))
      branch: feature 
      depth: 1

  - name: secrets.git
    type: git
    source:
      uri:         git@github.wdf.sap.corp:cc/secrets.git
      private_key: ((secrets-ssh-key))
      branch:      master
      depth: 1

  - name: daily
    type: time
    source: {interval: 24h}


resource_types:
  - name: time-version
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/time-version-resource
      tag: v2
  - name: slack-notification
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/slack-notification-resource
      tag: latest
  - name: gh-status
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/ghstatus-resource
      tag: latest

jobs:
  - name: master 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          trigger: true
      - aggregate:
        - task: kubernikus 
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_master
        - task: kubernikus-system 
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_master

  - name: feature 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: feature.builds
          trigger: true
      - aggregate:
        - task: kubernikus 
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_feature
        - task: kubernikus-system 
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_feature

  - name: e2e
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [master]
          trigger: true
      - task: e2e_tests
        file: kubernikus.builds/ci/task_e2e_tests.yaml
        params:
          <<: *auth_e2e

  - name: conformance 
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.builds
          resource: master.builds
          passed: [e2e]
        - get: daily
          trigger: true

  - name: prod 
    serial: true
    plan:
      - get: kubernikus.builds
        resource: master.builds
        passed: [e2e]

  - name: emea 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [prod]
          trigger: true
      - aggregate:
        - task: kubernikus_eu-nl-1
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_eu-nl-1
        - task: kubernikus-system_eu-nl-1
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_eu-nl-1

  - name: asia
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [prod]
          trigger: true

  - name: americas 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [prod]
          trigger: true
      - aggregate:
        - task: kubernikus_na-us-1
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_na-us-1
        - task: kubernikus-system_na-us-1
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_na-us-1

  - name: admin 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: master.builds
          passed: [prod]
          trigger: true
      - aggregate:
        - task: k-master 
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-master
            GITHUB_TOKEN: ((github-access-token))
        - task: k-feature
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-feature
            GITHUB_TOKEN: ((github-access-token))
        - task: k-eu-nl-1
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-eu-nl-1
            GITHUB_TOKEN: ((github-access-token))
        - task: k-na-us-1
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-na-us-1
            GITHUB_TOKEN: ((github-access-token))

  - name: staging 
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: feature.builds
          passed: [feature]
          trigger: true
      - aggregate:
        - task: k-staging
          file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
          params:
            REGION: admin
            KUBERNIKUS_NAME: k-staging
            GITHUB_TOKEN: ((github-access-token))
        - task: kubernikus
          file: kubernikus.builds/ci/task_helm_kubernikus.yaml
          params:
            <<: *auth_staging
        - task: kubernikus-system
          file: kubernikus.builds/ci/task_helm_kubernikus-system.yaml
          params:
            <<: *auth_staging

  - name: qa
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: kubernikus.builds
          resource: feature.builds
          passed: [feature]
          trigger: true


