post_failure_to_slack: &post_failure_to_slack
  put: slack-alert
  params:
    channel: '#kubernikus'
    username: 'Concourse'
    icon_emoji: ':airplane:'
    silent: 'true'
    text: |
      :boom: <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME $BUILD_JOB_NAME job #$BUILD_NAME failed>

resources:
  - name: kubernikus.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: master
      depth: 1
      params:
        ignore_paths: ["contrib/**", "docs/**", "ci/**"]

  - name: charts.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: master
      depth: 1
      params:
        paths: ["charts/**"]
        ignore_paths: ["*"]

  - name: contrib.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: master
      depth: 1
      params:
        paths: ["contrib/**"]
        ignore_paths: ["*"]

  - name: docs.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: master
      depth: 1
      params:
        paths: ["docs/**"]
        ignore_paths: ["*"]

  - name: pipeline.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: master
      depth: 1
      params:
        paths: ["ci/*"]

  - name: secrets.git
    type: git
    source:
      uri:         git@github.wdf.sap.corp:cc/secrets.git
      private_key: ((secrets-ssh-key))
      branch:      master
      depth: 1

  - name: version
    type: time-version-resource
    source:
      prefix: v
      property_name: VERSION
      check_every: 525600h

  - name: kubernikus-binaries.image
    type: docker-image
    source:
      repository: sapcc/kubernikus-binaries
      username:   ((docker-hub-username))
      password:   ((docker-hub-password))

  - name: kubernikus.image
    type: docker-image
    source:
      repository: sapcc/kubernikus
      username:   ((docker-hub-username))
      password:   ((docker-hub-password))

  - name: kubernikusctl.image
    type: docker-image
    source:
      repository: sapcc/kubernikusctl
      username:   ((docker-hub-username))
      password:   ((docker-hub-password))

  - name: kubernikus-kubectl.image
    type: docker-image
    source:
      repository: sapcc/kubernikus-kubectl
      username:   ((docker-hub-username))
      password:   ((docker-hub-password))

  - name: kubernikus-docs.image
    type: docker-image
    source:
      repository: sapcc/kubernikus-docs
      username:   ((docker-hub-username))
      password:   ((docker-hub-password))

  - name: kubernikus-docs-builder.image
    type: docker-image
    source:
      repository: sapcc/kubernikus-docs-builder
      username:   ((docker-hub-username))
      password:   ((docker-hub-password))

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-webhook-url}}

resource_types:
  - name: time-version-resource
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/time-version-resource
      tag: v2
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

groups:
  - name: kubernikus
    jobs:
      - docs
      - binaries 
      - package
      - staging
      - e2e
      - rollout
      - eu-nl-1
  - name: admin
    jobs:
      - admin_staging
      - rollout_admin
      - admin_eu-nl-1
  - name: kubernikus-system
    jobs:
      - staging_kubernikus-system
      - rollout_kubernikus-system
      - eu-nl-1_kubernikus-system
  - name: contrib
    jobs:
      - kubernikus-docs-builder
      - kubernikus-kubectl
  - name: docs
    jobs: 
      - docs
      - binaries 
      - package


jobs:

####################################################################################
#
# contrib
#
####################################################################################

  - name: kubernikus-docs-builder
    on_failure:
      <<: *post_failure_to_slack
    plan:
      - aggregate:
        - get: kubernetes.git
          resource: contrib.git
          trigger: true

      - put: kubernikus-docs-builder.image
        params:
          build: kubernetes.git/contrib/kubernikus-docs-builder
          tag: kubernetes.git/.git/HEAD
          tag_as_latest: true
          build_args:
            http_proxy: http://proxy.phl.sap.corp:8080
            https_proxy: http://proxy.phl.sap.corp:8080
            no_proxy: sap.corp,cloud.sap,127.0.0.1,localhost
        get_params:
          skip_download: true

  - name: kubernikus-kubectl
    on_failure:
      <<: *post_failure_to_slack
    plan:
      - aggregate:
        - get: kubernetes.git
          resource: contrib.git
          trigger: true
        - get: kubernikus-binaries.image
          passed: [binaries]
          trigger: true
  
      - task: kubernikus-binaries.properties
        file: kubernetes.git/ci/task_image_properties.yaml
        input_mapping: 
          image0: kubernikus-binaries.image 
          image1: kubernikus-binaries.image 
        output_mapping:
          image.properties: kubernikus-binaries.properties
        params:
          image0: KUBERNIKUS_BINARIES

      - put: kubernikus-docs-builder.image
        params:
          build: kubernetes.git/contrib/kubernikus-kubectl
          tag: kubernetes.git/.git/HEAD
          tag_as_latest: true
          build_args_file: kubernikus-binaries.properties/properties.json
          build_args:
            http_proxy: http://proxy.phl.sap.corp:8080
            https_proxy: http://proxy.phl.sap.corp:8080
            no_proxy: sap.corp,cloud.sap,127.0.0.1,localhost
        get_params:
          skip_download: true


####################################################################################
#
# docs 
#
####################################################################################

  - name: docs 
    on_failure:
      <<: *post_failure_to_slack
    plan:
      - aggregate:
        - get: kubernetes.git
          resource: docs.git
          trigger: true
        - get: kubernikus-docs-builder.image
          trigger: true
          passed: [kubernikus-docs-builder]
          params:
            skip_download: true

      - task: kubernikus-docs-builder.properties
        file: kubernetes.git/ci/task_image_properties.yaml
        input_mapping: 
          image0: kubernikus-docs-builder.image 
          image1: kubernikus-docs-builder.image 
        output_mapping:
          image.properties: kubernikus-docs-builder.properties
        params:
          image0: KUBERNIKUS_DOCS
        
      - put: kubernikus-docs.image
        params:
          build: kubernetes.git
          dockerfile: kubernetes.git/Dockerfile.kubernikus-docs
          tag: kubernetes.git/.git/HEAD
          tag_as_latest: true
          build_args_file: kubernikus-docs-builder.properties/properties.json
          build_args:
            http_proxy: http://proxy.phl.sap.corp:8080
            https_proxy: http://proxy.phl.sap.corp:8080
            no_proxy: sap.corp,cloud.sap,127.0.0.1,localhost
        get_params:
          skip_download: true


####################################################################################
#
# kubernikus
#
####################################################################################

  - name: binaries 
    serial: true
    on_failure:
      <<: *post_failure_to_slack
    plan:
      - get: kubernikus.git
        trigger: true

      - put: kubernikus-binaries.image
        params:
          build: kubernikus.git
          dockerfile: kubernikus.git/Dockerfile.kubernikus-binaries
          tag: kubernetes.git/.git/HEAD
          tag_as_latest: true
          build_args:
            http_proxy: http://proxy.phl.sap.corp:8080
            https_proxy: http://proxy.phl.sap.corp:8080
            no_proxy: sap.corp,cloud.sap,127.0.0.1,localhost
        get_params:
          skip_download: true


  - name: package
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
          passed: [binaries]
        - get: kubernikus-binaries.image
          trigger: true
          passed: [binaries]
          params:
            skip_download: true
        - get: kubernikus-docs.image
          passed: [docs]
          trigger: true
          params:
            skip_download: true
        - put: version

      - aggregate:
        - task: image.properties
          file: kubernikus.git/ci/task_image_properties.yaml
          input_mapping: 
            image0: kubernikus-docs.image 
            image1: kubernikus-binaries.image 
          output_mapping:
            image.properties: kubernikus-docs.properties
          params:
            image0: KUBERNIKUS_DOCS
            image1: KUBERNIKUS_BINARIES

      - aggregate:
        - put: kubernikus.image
          params:
            build: kubernikus.git
            dockerfile: kubernikus.git/Dockerfile.kubernikus
            tag: version/version
            build_args_file: images.properties/properties.json
            build_args:
              http_proxy: http://proxy.phl.sap.corp:8080
              https_proxy: http://proxy.phl.sap.corp:8080
              no_proxy: sap.corp,cloud.sap,127.0.0.1,localhost
          get_params:
            skip_download: true
        - put: kubernikusctl.image
          params:
            build: kubernikus.git
            dockerfile: kubernikus.git/Dockerfile.kubernikusctl
            tag: version/version
            tag_as_latest: true
            build_args_file: images.properties/properties.json
            build_args:
              http_proxy: http://proxy.phl.sap.corp:8080
              https_proxy: http://proxy.phl.sap.corp:8080
              no_proxy: sap.corp,cloud.sap,127.0.0.1,localhost
          get_params:
            skip_download: true
        - put: kubernikus-kubectl.image
          params:
            build: kubernikus.git/contrib/kubernikus-kubectl
            tag: version/version
            tag_as_latest: true
            cache: true 
            cache_tag: latest
            build_args_file: images.properties/properties.json
            build_args:
              http_proxy: http://proxy.phl.sap.corp:8080
              https_proxy: http://proxy.phl.sap.corp:8080
              no_proxy: sap.corp,cloud.sap,127.0.0.1,localhost
          get_params:
            skip_download: true

  - name: staging
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
        - get: version
          passed: [package]
          trigger: true
        - get: secrets.git
      - task: deploy
        file: kubernikus.git/ci/task_helm_kubernikus.yaml
        params:
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin 
          OS_PROJECT_NAME: kubernikus-staging
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-staging
          KUBERNIKUS_URL: https://k-staging.admin.cloud.sap

  - name: e2e
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
          passed: [staging]
          params:
            depth: 0
        - get: version
          passed: [staging]
          trigger: true

  - name: rollout
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
          passed: [e2e]
          params:
            depth: 0
        - get: version
          passed: [e2e]

  - name: eu-nl-1
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
          passed: [rollout]
        - get: version
          passed: [rollout]
          trigger: true
        - get: secrets.git
        - get: pipeline.git
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus.yaml
        params:
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin 
          OS_PROJECT_NAME: kubernikus
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-eu-nl-1
          KUBERNIKUS_URL: https://k-eu-nl-1.admin.cloud.sap
    on_failure:
      <<: *post_failure_to_slack

####################################################################################
#
# admin 
#
####################################################################################
#
  - name: admin_staging
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
        - get: secrets.git
        - get: version
          passed: [package]
          trigger: true
      - task: deploy
        file: kubernikus.git/ci/task_helm-admin_kubernikus.yaml
        params:
          REGION: admin
          KUBERNIKUS_NAME: k-staging
          GITHUB_TOKEN: ((github-access-token))

  - name: rollout_admin
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
          passed: [admin_staging]
          params:
            depth: 0
        - get: version
          passed: [admin_staging]
          trigger: true # remove for manual gate

  - name: admin_eu-nl-1
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
        - get: secrets.git
        - get: version
          passed: [rollout_admin]
          trigger: true
      - task: deploy
        file: kubernikus.git/ci/task_helm-admin_kubernikus.yaml
        params:
          REGION: admin
          KUBERNIKUS_NAME: k-eu-nl-1
          GITHUB_TOKEN: ((github-access-token))
    on_failure:
      <<: *post_failure_to_slack

####################################################################################
#
# kubernikus-system
#
####################################################################################

  - name: staging_kubernikus-system
    serial: true
    plan:
      - aggregate:
        - get: charts.git
        - get: secrets.git
        - get: pipeline.git
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus-system.yaml
        params:
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin 
          OS_PROJECT_NAME: kubernikus-staging
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-staging
          KUBERNIKUS_URL: https://k-staging.admin.cloud.sap

  - name: rollout_kubernikus-system
    serial: true
    plan:
      - aggregate:
        - get: charts.git
          passed: [staging_kubernikus-system]
          params:
            depth: 0

  - name: eu-nl-1_kubernikus-system
    serial: true
    plan:
      - aggregate:
        - get: charts.git
          passed: [rollout_kubernikus-system]
          trigger: true
        - get: secrets.git
        - get: pipeline.git
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus-system.yaml
        params:
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin 
          OS_PROJECT_NAME: kubernikus
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-eu-nl-1
          KUBERNIKUS_URL: https://k-eu-nl-1.admin.cloud.sap
