post_failure_to_slack: &post_failure_to_slack
  put: slack-alert
  params:
    channel: '#kubernikus'
    username: 'Concourse'
    icon_emoji: ':airplane:'
    silent: 'true'
    text: |
      :boom: <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME $BUILD_JOB_NAME job #$BUILD_NAME failed>

resources:
  #- name: kubernikusctl.version
  #  type: time-version
  #  check_every: 525600h

  - name: kubernikusctl.release
    type: github-release
    source:
      owner: sapcc
      repository: kubernikus
      access_token: ((github-com-access-token))

  - name: kubernikus.builds
    type: gh-status
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      owner:    sapcc
      repo:     kubernikus
      access_token: ((github-com-access-token))
      branch: master
      depth: 1
      ignore_paths: ["charts", "ci"]

  - name: charts.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: master
      depth: 1
      paths: ["charts"]

  - name: pipeline.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: master
      depth: 1
      paths: ["ci"]

  - name: secrets.git
    type: git
    source:
      uri:         git@github.wdf.sap.corp:cc/secrets.git
      private_key: ((secrets-ssh-key))
      branch:      master
      depth: 1

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-webhook-url}}

resource_types:
  - name: time-version
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/time-version-resource
      tag: v2
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
  - name: gh-status
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/ghstatus-resource
      tag: latest
groups:
  - name: kubernikus
    jobs:
      - cli
      - staging
      - e2e
      - rollout
      - eu-nl-1
      - na-us-1
  - name: admin
    jobs:
      - admin_staging
      - rollout_admin
      - admin_eu-nl-1
      - admin_na-us-1
  - name: kubernikus-system
    jobs:
      - staging_kubernikus-system
      - rollout_kubernikus-system
      - eu-nl-1_kubernikus-system
      - na-us-1_kubernikus-system

jobs:
####################################################################################
#
# kubernikus
#
####################################################################################

  - name: cli
    plan:
      - aggregate:
        - get: kubernikus.builds
          trigger: true
      - task: build
        file: kubernikus.builds/ci/task_cli.yaml
      - put: kubernikusctl.release
        params:
          name: binaries/tag
          tag: binaries/tag
          tag_prefix: v
          commitish: binaries/commitish
          globs:
            - binaries/kubernikusctl*
        get_params:
          globs: []

  - name: staging
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: pipeline.git
        - get: kubernikus.builds
          trigger: true
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus.yaml
        params:
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus-staging
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-staging
          KUBERNIKUS_URL: https://k-staging.admin.cloud.sap
    on_failure:
      <<: *post_failure_to_slack

  - name: e2e
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [staging]
        trigger: true

  - name: rollout
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [staging]
        passed: [e2e]
        trigger: true

  - name: eu-nl-1
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: pipeline.git
        - get: kubernikus.builds
          passed: [rollout]
          trigger: true
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus.yaml
        params:
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-eu-nl-1
          KUBERNIKUS_URL: https://k-eu-nl-1.admin.cloud.sap
    on_failure:
      <<: *post_failure_to_slack

  - name: na-us-1
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: pipeline.git
        - get: kubernikus.builds
          passed: [rollout]
          trigger: true
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus.yaml
        params:
          OS_AUTH_URL: https://identity-3.na-us-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-na-us-1-username}}
          OS_PASSWORD: {{kubernikus-na-us-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-na-us-1
          KUBERNIKUS_URL: https://k-na-us-1.admin.cloud.sap
    on_failure:
      <<: *post_failure_to_slack

####################################################################################
#
# admin
#
####################################################################################
#
  - name: admin_staging
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: pipeline.git
        - get: kubernikus.builds
          trigger: true
      - task: deploy
        file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
        params:
          REGION: admin
          KUBERNIKUS_NAME: k-staging
          GITHUB_TOKEN: ((github-access-token))
    on_failure:
      <<: *post_failure_to_slack

  - name: rollout_admin
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [admin_staging]
        trigger: true

  - name: admin_eu-nl-1
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: pipeline.git
        - get: kubernikus.builds
          passed: [rollout_admin]
          trigger: true
      - task: deploy
        file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
        params:
          REGION: admin
          KUBERNIKUS_NAME: k-eu-nl-1
          GITHUB_TOKEN: ((github-access-token))
    on_failure:
      <<: *post_failure_to_slack

  - name: admin_na-us-1
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: pipeline.git
        - get: kubernikus.builds
          passed: [rollout_admin]
          trigger: true
      - task: deploy
        file: kubernikus.builds/ci/task_helm-admin_kubernikus.yaml
        params:
          REGION: admin
          KUBERNIKUS_NAME: k-na-us-1
          GITHUB_TOKEN: ((github-access-token))
    on_failure:
      <<: *post_failure_to_slack

####################################################################################
#
# kubernikus-system
#
####################################################################################

  - name: staging_kubernikus-system
    serial: true
    plan:
      - aggregate:
        - get: charts.git
          trigger: true
        - get: secrets.git
        - get: pipeline.git
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus-system.yaml
        params:
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus-staging
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-staging
          KUBERNIKUS_URL: https://k-staging.admin.cloud.sap
      - task: reload prometheus configuration
        file: pipeline.git/ci/task_reload_prometheus_config.yaml
        params:
          NAMESPACE: kubernikus-system
          DELAY_SECONDS: 30
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus-staging
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-staging
          KUBERNIKUS_URL: https://k-staging.admin.cloud.sap
    on_failure:
      <<: *post_failure_to_slack

  - name: rollout_kubernikus-system
    serial: true
    plan:
      - get: charts.git
        passed: [staging_kubernikus-system]
        trigger: true

  - name: eu-nl-1_kubernikus-system
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: pipeline.git
        - get: charts.git
          passed: [rollout_kubernikus-system]
          trigger: true
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus-system.yaml
        params:
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-eu-nl-1
          KUBERNIKUS_URL: https://k-eu-nl-1.admin.cloud.sap
      - task: reload prometheus configuration
        file: pipeline.git/ci/task_reload_prometheus_config.yaml
        params:
          NAMESPACE: kubernikus-system
          DELAY_SECONDS: 30
          OS_AUTH_URL: https://identity-3.eu-nl-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-eu-nl-1-username}}
          OS_PASSWORD: {{kubernikus-eu-nl-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-eu-nl-1
          KUBERNIKUS_URL: https://k-eu-nl-1.admin.cloud.sap
    on_failure:
      <<: *post_failure_to_slack

  - name: na-us-1_kubernikus-system
    serial: true
    plan:
      - aggregate:
        - get: secrets.git
        - get: pipeline.git
        - get: charts.git
          passed: [rollout_kubernikus-system]
          trigger: true
      - task: deploy
        file: pipeline.git/ci/task_helm_kubernikus-system.yaml
        params:
          OS_AUTH_URL: https://identity-3.na-us-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-na-us-1-username}}
          OS_PASSWORD: {{kubernikus-na-us-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-na-us-1
          KUBERNIKUS_URL: https://k-na-us-1.admin.cloud.sap
      - task: reload prometheus configuration
        file: pipeline.git/ci/task_reload_prometheus_config.yaml
        params:
          NAMESPACE: kubernikus-system
          DELAY_SECONDS: 30
          OS_AUTH_URL: https://identity-3.na-us-1.cloud.sap/v3
          OS_USERNAME: {{kubernikus-na-us-1-username}}
          OS_PASSWORD: {{kubernikus-na-us-1-password}}
          OS_USER_DOMAIN_NAME: ccadmin
          OS_PROJECT_NAME: kubernikus
          OS_PROJECT_DOMAIN_NAME: ccadmin
          KUBERNIKUS_NAME: k-na-us-1
          KUBERNIKUS_URL: https://k-na-us-1.admin.cloud.sap
    on_failure:
      <<: *post_failure_to_slack
