---
platform: 'linux'

image_resource:
  type: docker-image
  source:
    repository: sapcc/kubernikus-kubectl
    tag: 'latest'

inputs:
  - name: charts.git
  - name: secrets.git

run:
  path: /bin/sh
  args:
    - -c
    - |
      set -exo pipefail

      k() {
        local OPERATION="$1"
        shift
        kubectl "${OPERATION}" --namespace="${NAMESPACE}" "$@"
      }

      echo ">> Waiting ${DELAY_SECONDS} seconds before reloading prometheus configuration"
      sleep "${DELAY_SECONDS}"

      kubernikusctl auth init

      k get pods -o jsonpath='{.items[*].metadata.name}'| tr ' ' '\n' | grep prometheus | while read POD ; do
        echo "Reloading configuration for ${POD}..."
        k exec "${POD}" -- kill -HUP 1
      done

params:
  NAMESPACE:
  DELAY_SECONDS:
  OS_AUTH_URL:
  OS_USERNAME:
  OS_PASSWORD:
  OS_USER_DOMAIN_NAME:
  OS_PROJECT_NAME:
  OS_PROJECT_DOMAIN_NAME:
  KUBERNIKUS_NAME:
  KUBERNIKUS_URL:
