// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// CreateClusterCreatedCode is the HTTP code returned for type CreateClusterCreated
const CreateClusterCreatedCode int = 201

/*CreateClusterCreated OK

swagger:response createClusterCreated
*/
type CreateClusterCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Cluster `json:"body,omitempty"`
}

// NewCreateClusterCreated creates CreateClusterCreated with default headers values
func NewCreateClusterCreated() *CreateClusterCreated {
	return &CreateClusterCreated{}
}

// WithPayload adds the payload to the create cluster created response
func (o *CreateClusterCreated) WithPayload(payload *models.Cluster) *CreateClusterCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cluster created response
func (o *CreateClusterCreated) SetPayload(payload *models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateClusterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateClusterDefault Error

swagger:response createClusterDefault
*/
type CreateClusterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateClusterDefault creates CreateClusterDefault with default headers values
func NewCreateClusterDefault(code int) *CreateClusterDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateClusterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create cluster default response
func (o *CreateClusterDefault) WithStatusCode(code int) *CreateClusterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create cluster default response
func (o *CreateClusterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create cluster default response
func (o *CreateClusterDefault) WithPayload(payload *models.Error) *CreateClusterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cluster default response
func (o *CreateClusterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateClusterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
