// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// CreateClusterHandlerFunc turns a function with the right signature into a create cluster handler
type CreateClusterHandlerFunc func(CreateClusterParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateClusterHandlerFunc) Handle(params CreateClusterParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateClusterHandler interface for that can handle valid create cluster params
type CreateClusterHandler interface {
	Handle(CreateClusterParams, *models.Principal) middleware.Responder
}

// NewCreateCluster creates a new http.Handler for the create cluster operation
func NewCreateCluster(ctx *middleware.Context, handler CreateClusterHandler) *CreateCluster {
	return &CreateCluster{Context: ctx, Handler: handler}
}

/*CreateCluster swagger:route POST /api/v1/clusters/ createCluster

Create a cluster

*/
type CreateCluster struct {
	Context *middleware.Context
	Handler CreateClusterHandler
}

func (o *CreateCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateClusterParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
