// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// DeleteClusterHandlerFunc turns a function with the right signature into a delete cluster handler
type DeleteClusterHandlerFunc func(DeleteClusterParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteClusterHandlerFunc) Handle(params DeleteClusterParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteClusterHandler interface for that can handle valid delete cluster params
type DeleteClusterHandler interface {
	Handle(DeleteClusterParams, *models.Principal) middleware.Responder
}

// NewDeleteCluster creates a new http.Handler for the delete cluster operation
func NewDeleteCluster(ctx *middleware.Context, handler DeleteClusterHandler) *DeleteCluster {
	return &DeleteCluster{Context: ctx, Handler: handler}
}

/*DeleteCluster swagger:route DELETE /api/v1/clusters/{name} deleteCluster

Delete the specified cluser

*/
type DeleteCluster struct {
	Context *middleware.Context
	Handler DeleteClusterHandler
}

func (o *DeleteCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteClusterParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
