// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetClusterIgnitionHandlerFunc turns a function with the right signature into a get cluster ignition handler
type GetClusterIgnitionHandlerFunc func(GetClusterIgnitionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClusterIgnitionHandlerFunc) Handle(params GetClusterIgnitionParams) middleware.Responder {
	return fn(params)
}

// GetClusterIgnitionHandler interface for that can handle valid get cluster ignition params
type GetClusterIgnitionHandler interface {
	Handle(GetClusterIgnitionParams) middleware.Responder
}

// NewGetClusterIgnition creates a new http.Handler for the get cluster ignition operation
func NewGetClusterIgnition(ctx *middleware.Context, handler GetClusterIgnitionHandler) *GetClusterIgnition {
	return &GetClusterIgnition{Context: ctx, Handler: handler}
}

/*GetClusterIgnition swagger:route GET /api/v1/clusters/{name}/ignition getClusterIgnition

Get Ignition Config for Node in this Cluster

*/
type GetClusterIgnition struct {
	Context *middleware.Context
	Handler GetClusterIgnitionHandler
}

func (o *GetClusterIgnition) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetClusterIgnitionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
