// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/sapcc/kubernikus/pkg/api/models"
)

// GetClusterValuesOKCode is the HTTP code returned for type GetClusterValuesOK
const GetClusterValuesOKCode int = 200

/*GetClusterValuesOK OK

swagger:response getClusterValuesOK
*/
type GetClusterValuesOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetClusterValuesOKBody `json:"body,omitempty"`
}

// NewGetClusterValuesOK creates GetClusterValuesOK with default headers values
func NewGetClusterValuesOK() *GetClusterValuesOK {

	return &GetClusterValuesOK{}
}

// WithPayload adds the payload to the get cluster values o k response
func (o *GetClusterValuesOK) WithPayload(payload *models.GetClusterValuesOKBody) *GetClusterValuesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster values o k response
func (o *GetClusterValuesOK) SetPayload(payload *models.GetClusterValuesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterValuesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetClusterValuesDefault Error

swagger:response getClusterValuesDefault
*/
type GetClusterValuesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterValuesDefault creates GetClusterValuesDefault with default headers values
func NewGetClusterValuesDefault(code int) *GetClusterValuesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetClusterValuesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get cluster values default response
func (o *GetClusterValuesDefault) WithStatusCode(code int) *GetClusterValuesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get cluster values default response
func (o *GetClusterValuesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get cluster values default response
func (o *GetClusterValuesDefault) WithPayload(payload *models.Error) *GetClusterValuesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster values default response
func (o *GetClusterValuesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterValuesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
