package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetAPIOKCode is the HTTP code returned for type GetAPIOK
const GetAPIOKCode int = 200

/*GetAPIOK OK

swagger:response getApiOK
*/
type GetAPIOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIVersions `json:"body,omitempty"`
}

// NewGetAPIOK creates GetAPIOK with default headers values
func NewGetAPIOK() *GetAPIOK {
	return &GetAPIOK{}
}

// WithPayload adds the payload to the get Api o k response
func (o *GetAPIOK) WithPayload(payload *models.APIVersions) *GetAPIOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api o k response
func (o *GetAPIOK) SetPayload(payload *models.APIVersions) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAPIUnauthorizedCode is the HTTP code returned for type GetAPIUnauthorized
const GetAPIUnauthorizedCode int = 401

/*GetAPIUnauthorized Unauthorized

swagger:response getApiUnauthorized
*/
type GetAPIUnauthorized struct {
}

// NewGetAPIUnauthorized creates GetAPIUnauthorized with default headers values
func NewGetAPIUnauthorized() *GetAPIUnauthorized {
	return &GetAPIUnauthorized{}
}

// WriteResponse to the client
func (o *GetAPIUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}
