// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/sapcc/kubernikus/pkg/api/models"
)

// GetClusterValuesHandlerFunc turns a function with the right signature into a get cluster values handler
type GetClusterValuesHandlerFunc func(GetClusterValuesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClusterValuesHandlerFunc) Handle(params GetClusterValuesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetClusterValuesHandler interface for that can handle valid get cluster values params
type GetClusterValuesHandler interface {
	Handle(GetClusterValuesParams, *models.Principal) middleware.Responder
}

// NewGetClusterValues creates a new http.Handler for the get cluster values operation
func NewGetClusterValues(ctx *middleware.Context, handler GetClusterValuesHandler) *GetClusterValues {
	return &GetClusterValues{Context: ctx, Handler: handler}
}

/*GetClusterValues swagger:route GET /api/v1/{account}/clusters/{name}/values getClusterValues

Get values for cluster chart (admin-only)

*/
type GetClusterValues struct {
	Context *middleware.Context
	Handler GetClusterValuesHandler
}

func (o *GetClusterValues) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetClusterValuesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
