// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetClusterEventsOKCode is the HTTP code returned for type GetClusterEventsOK
const GetClusterEventsOKCode int = 200

/*GetClusterEventsOK OK

swagger:response getClusterEventsOK
*/
type GetClusterEventsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Event `json:"body,omitempty"`
}

// NewGetClusterEventsOK creates GetClusterEventsOK with default headers values
func NewGetClusterEventsOK() *GetClusterEventsOK {
	return &GetClusterEventsOK{}
}

// WithPayload adds the payload to the get cluster events o k response
func (o *GetClusterEventsOK) WithPayload(payload []*models.Event) *GetClusterEventsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster events o k response
func (o *GetClusterEventsOK) SetPayload(payload []*models.Event) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterEventsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Event, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetClusterEventsDefault Error

swagger:response getClusterEventsDefault
*/
type GetClusterEventsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterEventsDefault creates GetClusterEventsDefault with default headers values
func NewGetClusterEventsDefault(code int) *GetClusterEventsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetClusterEventsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get cluster events default response
func (o *GetClusterEventsDefault) WithStatusCode(code int) *GetClusterEventsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get cluster events default response
func (o *GetClusterEventsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get cluster events default response
func (o *GetClusterEventsDefault) WithPayload(payload *models.Error) *GetClusterEventsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster events default response
func (o *GetClusterEventsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterEventsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
