// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetOpenstackMetadataOKCode is the HTTP code returned for type GetOpenstackMetadataOK
const GetOpenstackMetadataOKCode int = 200

/*
GetOpenstackMetadataOK OK

swagger:response getOpenstackMetadataOK
*/
type GetOpenstackMetadataOK struct {

	/*
	  In: Body
	*/
	Payload *models.OpenstackMetadata `json:"body,omitempty"`
}

// NewGetOpenstackMetadataOK creates GetOpenstackMetadataOK with default headers values
func NewGetOpenstackMetadataOK() *GetOpenstackMetadataOK {

	return &GetOpenstackMetadataOK{}
}

// WithPayload adds the payload to the get openstack metadata o k response
func (o *GetOpenstackMetadataOK) WithPayload(payload *models.OpenstackMetadata) *GetOpenstackMetadataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get openstack metadata o k response
func (o *GetOpenstackMetadataOK) SetPayload(payload *models.OpenstackMetadata) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOpenstackMetadataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetOpenstackMetadataDefault Error

swagger:response getOpenstackMetadataDefault
*/
type GetOpenstackMetadataDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOpenstackMetadataDefault creates GetOpenstackMetadataDefault with default headers values
func NewGetOpenstackMetadataDefault(code int) *GetOpenstackMetadataDefault {
	if code <= 0 {
		code = 500
	}

	return &GetOpenstackMetadataDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get openstack metadata default response
func (o *GetOpenstackMetadataDefault) WithStatusCode(code int) *GetOpenstackMetadataDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get openstack metadata default response
func (o *GetOpenstackMetadataDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get openstack metadata default response
func (o *GetOpenstackMetadataDefault) WithPayload(payload *models.Error) *GetOpenstackMetadataDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get openstack metadata default response
func (o *GetOpenstackMetadataDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOpenstackMetadataDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
