package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetAPIV1ClustersNameOKCode is the HTTP code returned for type GetAPIV1ClustersNameOK
const GetAPIV1ClustersNameOKCode int = 200

/*GetAPIV1ClustersNameOK OK

swagger:response getApiV1ClustersNameOK
*/
type GetAPIV1ClustersNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cluster `json:"body,omitempty"`
}

// NewGetAPIV1ClustersNameOK creates GetAPIV1ClustersNameOK with default headers values
func NewGetAPIV1ClustersNameOK() *GetAPIV1ClustersNameOK {
	return &GetAPIV1ClustersNameOK{}
}

// WithPayload adds the payload to the get Api v1 clusters name o k response
func (o *GetAPIV1ClustersNameOK) WithPayload(payload *models.Cluster) *GetAPIV1ClustersNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api v1 clusters name o k response
func (o *GetAPIV1ClustersNameOK) SetPayload(payload *models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIV1ClustersNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
