// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/sapcc/kubernikus/pkg/api/models"
)

// GetBootstrapConfigHandlerFunc turns a function with the right signature into a get bootstrap config handler
type GetBootstrapConfigHandlerFunc func(GetBootstrapConfigParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBootstrapConfigHandlerFunc) Handle(params GetBootstrapConfigParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetBootstrapConfigHandler interface for that can handle valid get bootstrap config params
type GetBootstrapConfigHandler interface {
	Handle(GetBootstrapConfigParams, *models.Principal) middleware.Responder
}

// NewGetBootstrapConfig creates a new http.Handler for the get bootstrap config operation
func NewGetBootstrapConfig(ctx *middleware.Context, handler GetBootstrapConfigHandler) *GetBootstrapConfig {
	return &GetBootstrapConfig{Context: ctx, Handler: handler}
}

/*GetBootstrapConfig swagger:route GET /api/v1/clusters/{name}/bootstrap getBootstrapConfig

Get bootstrap config to onboard a node

*/
type GetBootstrapConfig struct {
	Context *middleware.Context
	Handler GetBootstrapConfigHandler
}

func (o *GetBootstrapConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBootstrapConfigParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
