// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/sapcc/kubernikus/pkg/api/models"
)

// GetBoostrapConfigOKCode is the HTTP code returned for type GetBoostrapConfigOK
const GetBoostrapConfigOKCode int = 200

/*GetBoostrapConfigOK OK

swagger:response getBoostrapConfigOK
*/
type GetBoostrapConfigOK struct {

	/*
	  In: Body
	*/
	Payload *models.Credentials `json:"body,omitempty"`
}

// NewGetBoostrapConfigOK creates GetBoostrapConfigOK with default headers values
func NewGetBoostrapConfigOK() *GetBoostrapConfigOK {

	return &GetBoostrapConfigOK{}
}

// WithPayload adds the payload to the get boostrap config o k response
func (o *GetBoostrapConfigOK) WithPayload(payload *models.Credentials) *GetBoostrapConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get boostrap config o k response
func (o *GetBoostrapConfigOK) SetPayload(payload *models.Credentials) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBoostrapConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetBoostrapConfigDefault Error

swagger:response getBoostrapConfigDefault
*/
type GetBoostrapConfigDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBoostrapConfigDefault creates GetBoostrapConfigDefault with default headers values
func NewGetBoostrapConfigDefault(code int) *GetBoostrapConfigDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBoostrapConfigDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get boostrap config default response
func (o *GetBoostrapConfigDefault) WithStatusCode(code int) *GetBoostrapConfigDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get boostrap config default response
func (o *GetBoostrapConfigDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get boostrap config default response
func (o *GetBoostrapConfigDefault) WithPayload(payload *models.Error) *GetBoostrapConfigDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get boostrap config default response
func (o *GetBoostrapConfigDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBoostrapConfigDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
