// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetClusterCredentialsKubeadmHandlerFunc turns a function with the right signature into a get cluster credentials kubeadm handler
type GetClusterCredentialsKubeadmHandlerFunc func(GetClusterCredentialsKubeadmParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClusterCredentialsKubeadmHandlerFunc) Handle(params GetClusterCredentialsKubeadmParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetClusterCredentialsKubeadmHandler interface for that can handle valid get cluster credentials kubeadm params
type GetClusterCredentialsKubeadmHandler interface {
	Handle(GetClusterCredentialsKubeadmParams, *models.Principal) middleware.Responder
}

// NewGetClusterCredentialsKubeadm creates a new http.Handler for the get cluster credentials kubeadm operation
func NewGetClusterCredentialsKubeadm(ctx *middleware.Context, handler GetClusterCredentialsKubeadmHandler) *GetClusterCredentialsKubeadm {
	return &GetClusterCredentialsKubeadm{Context: ctx, Handler: handler}
}

/*
	GetClusterCredentialsKubeadm swagger:route GET /api/v1/clusters/{name}/credentials/kubeadm getClusterCredentialsKubeadm

Get CA secret for kubeadm
*/
type GetClusterCredentialsKubeadm struct {
	Context *middleware.Context
	Handler GetClusterCredentialsKubeadmHandler
}

func (o *GetClusterCredentialsKubeadm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetClusterCredentialsKubeadmParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
