package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// GetAPIV1ClustersOKCode is the HTTP code returned for type GetAPIV1ClustersOK
const GetAPIV1ClustersOKCode int = 200

/*GetAPIV1ClustersOK OK

swagger:response getApiV1ClustersOK
*/
type GetAPIV1ClustersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Cluster `json:"body,omitempty"`
}

// NewGetAPIV1ClustersOK creates GetAPIV1ClustersOK with default headers values
func NewGetAPIV1ClustersOK() *GetAPIV1ClustersOK {
	return &GetAPIV1ClustersOK{}
}

// WithPayload adds the payload to the get Api v1 clusters o k response
func (o *GetAPIV1ClustersOK) WithPayload(payload []*models.Cluster) *GetAPIV1ClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api v1 clusters o k response
func (o *GetAPIV1ClustersOK) SetPayload(payload []*models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIV1ClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Cluster, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
