// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/sapcc/kubernikus/pkg/api/models"
)

// ListClustersOKCode is the HTTP code returned for type ListClustersOK
const ListClustersOKCode int = 200

/*ListClustersOK OK

swagger:response listClustersOK
*/
type ListClustersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Kluster `json:"body,omitempty"`
}

// NewListClustersOK creates ListClustersOK with default headers values
func NewListClustersOK() *ListClustersOK {

	return &ListClustersOK{}
}

// WithPayload adds the payload to the list clusters o k response
func (o *ListClustersOK) WithPayload(payload []*models.Kluster) *ListClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters o k response
func (o *ListClustersOK) SetPayload(payload []*models.Kluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Kluster, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListClustersDefault Error

swagger:response listClustersDefault
*/
type ListClustersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListClustersDefault creates ListClustersDefault with default headers values
func NewListClustersDefault(code int) *ListClustersDefault {
	if code <= 0 {
		code = 500
	}

	return &ListClustersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list clusters default response
func (o *ListClustersDefault) WithStatusCode(code int) *ListClustersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list clusters default response
func (o *ListClustersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list clusters default response
func (o *ListClustersDefault) WithPayload(payload *models.Error) *ListClustersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters default response
func (o *ListClustersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
