package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// ListClustersOKCode is the HTTP code returned for type ListClustersOK
const ListClustersOKCode int = 200

/*ListClustersOK OK

swagger:response listClustersOK
*/
type ListClustersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Cluster `json:"body,omitempty"`
}

// NewListClustersOK creates ListClustersOK with default headers values
func NewListClustersOK() *ListClustersOK {
	return &ListClustersOK{}
}

// WithPayload adds the payload to the list clusters o k response
func (o *ListClustersOK) WithPayload(payload []*models.Cluster) *ListClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters o k response
func (o *ListClustersOK) SetPayload(payload []*models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Cluster, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
