// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// PatchClusterHandlerFunc turns a function with the right signature into a patch cluster handler
type PatchClusterHandlerFunc func(PatchClusterParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchClusterHandlerFunc) Handle(params PatchClusterParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PatchClusterHandler interface for that can handle valid patch cluster params
type PatchClusterHandler interface {
	Handle(PatchClusterParams, *models.Principal) middleware.Responder
}

// NewPatchCluster creates a new http.Handler for the patch cluster operation
func NewPatchCluster(ctx *middleware.Context, handler PatchClusterHandler) *PatchCluster {
	return &PatchCluster{Context: ctx, Handler: handler}
}

/*PatchCluster swagger:route PATCH /api/v1/clusters/{name} patchCluster

Patch the specified cluser

*/
type PatchCluster struct {
	Context *middleware.Context
	Handler PatchClusterHandler
}

func (o *PatchCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchClusterParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
