// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// PatchClusterOKCode is the HTTP code returned for type PatchClusterOK
const PatchClusterOKCode int = 200

/*PatchClusterOK OK

swagger:response patchClusterOK
*/
type PatchClusterOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cluster `json:"body,omitempty"`
}

// NewPatchClusterOK creates PatchClusterOK with default headers values
func NewPatchClusterOK() *PatchClusterOK {
	return &PatchClusterOK{}
}

// WithPayload adds the payload to the patch cluster o k response
func (o *PatchClusterOK) WithPayload(payload *models.Cluster) *PatchClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch cluster o k response
func (o *PatchClusterOK) SetPayload(payload *models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PatchClusterDefault Error

swagger:response patchClusterDefault
*/
type PatchClusterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchClusterDefault creates PatchClusterDefault with default headers values
func NewPatchClusterDefault(code int) *PatchClusterDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchClusterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch cluster default response
func (o *PatchClusterDefault) WithStatusCode(code int) *PatchClusterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch cluster default response
func (o *PatchClusterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch cluster default response
func (o *PatchClusterDefault) WithPayload(payload *models.Error) *PatchClusterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch cluster default response
func (o *PatchClusterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchClusterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
