// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// ShowClusterOKCode is the HTTP code returned for type ShowClusterOK
const ShowClusterOKCode int = 200

/*ShowClusterOK OK

swagger:response showClusterOK
*/
type ShowClusterOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cluster `json:"body,omitempty"`
}

// NewShowClusterOK creates ShowClusterOK with default headers values
func NewShowClusterOK() *ShowClusterOK {
	return &ShowClusterOK{}
}

// WithPayload adds the payload to the show cluster o k response
func (o *ShowClusterOK) WithPayload(payload *models.Cluster) *ShowClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the show cluster o k response
func (o *ShowClusterOK) SetPayload(payload *models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShowClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ShowClusterDefault Error

swagger:response showClusterDefault
*/
type ShowClusterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewShowClusterDefault creates ShowClusterDefault with default headers values
func NewShowClusterDefault(code int) *ShowClusterDefault {
	if code <= 0 {
		code = 500
	}

	return &ShowClusterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the show cluster default response
func (o *ShowClusterDefault) WithStatusCode(code int) *ShowClusterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the show cluster default response
func (o *ShowClusterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the show cluster default response
func (o *ShowClusterDefault) WithPayload(payload *models.Error) *ShowClusterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the show cluster default response
func (o *ShowClusterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShowClusterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
