// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/kubernikus/pkg/api/models"
)

// UpdateClusterOKCode is the HTTP code returned for type UpdateClusterOK
const UpdateClusterOKCode int = 200

/*
UpdateClusterOK OK

swagger:response updateClusterOK
*/
type UpdateClusterOK struct {

	/*
	  In: Body
	*/
	Payload *models.Kluster `json:"body,omitempty"`
}

// NewUpdateClusterOK creates UpdateClusterOK with default headers values
func NewUpdateClusterOK() *UpdateClusterOK {

	return &UpdateClusterOK{}
}

// WithPayload adds the payload to the update cluster o k response
func (o *UpdateClusterOK) WithPayload(payload *models.Kluster) *UpdateClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cluster o k response
func (o *UpdateClusterOK) SetPayload(payload *models.Kluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
UpdateClusterDefault Error

swagger:response updateClusterDefault
*/
type UpdateClusterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateClusterDefault creates UpdateClusterDefault with default headers values
func NewUpdateClusterDefault(code int) *UpdateClusterDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateClusterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update cluster default response
func (o *UpdateClusterDefault) WithStatusCode(code int) *UpdateClusterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update cluster default response
func (o *UpdateClusterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update cluster default response
func (o *UpdateClusterDefault) WithPayload(payload *models.Error) *UpdateClusterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cluster default response
func (o *UpdateClusterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateClusterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
